"""
Create Unit 5 Lecture 4: Single DOF Vibrations
Bridge from multi-DOF to vibrations analysis
Duration: ~90 minutes
"""

import json
import os

# Output paths
output_dir = "notebooks/Teacher"
output_path = os.path.join(output_dir, "T_U5_L4_Single_DOF_Vibrations.ipynb")

# Initialize notebook structure
notebook = {
    "cells": [],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.8.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

# Cell 1: Header
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# Unit 5 Lecture 4: Single Degree of Freedom (SDOF) Vibrations\n",
        "## Free Response & Damping\n",
        "\n",
        "### Learning Objectives\n",
        "1. Understand SDOF vibration fundamentals\n",
        "2. Derive natural frequency $\\omega_n = \\sqrt{k/m}$\n",
        "3. Analyze damping effects: underdamped, critically damped, overdamped\n",
        "4. Calculate damping ratio $\\zeta$ and logarithmic decrement\n",
        "5. Understand phase portraits and energy dissipation\n",
        "\n",
        "### Context\n",
        "**Bridge from multi-DOF to vibrations**:\n",
        "- Last lecture: Multi-DOF systems → normal modes\n",
        "- This lecture: **Single mode analysis** in depth\n",
        "- Each mode of multi-DOF system behaves like SDOF!\n",
        "\n",
        "**Why SDOF matters**:\n",
        "- **Foundation**: Building block for all vibration analysis\n",
        "- **Design**: Predict natural frequencies (avoid resonance!)\n",
        "- **Testing**: Extract modal parameters from experiments\n",
        "- **Real systems**: Many can be approximated as SDOF (pendulum, cantilever beam, car suspension)\n",
        "\n",
        "### Key Concepts\n",
        "\n",
        "**Standard SDOF equation**:\n",
        "$$m\\ddot{x} + c\\dot{x} + kx = 0$$\n",
        "\n",
        "**Parameters**:\n",
        "- $\\omega_n = \\sqrt{k/m}$ → **Natural frequency** (rad/s)\n",
        "- $f_n = \\omega_n / (2\\pi)$ → Natural frequency (Hz)\n",
        "- $T_n = 1/f_n = 2\\pi/\\omega_n$ → Period (s)\n",
        "- $\\zeta = c/(2\\sqrt{km}) = c/c_c$ → **Damping ratio** (dimensionless)\n",
        "- $c_c = 2\\sqrt{km} = 2m\\omega_n$ → Critical damping\n",
        "\n",
        "**Damping regimes**:\n",
        "1. **Underdamped** ($\\zeta < 1$): Oscillates with decay\n",
        "2. **Critically damped** ($\\zeta = 1$): Fastest return without overshoot\n",
        "3. **Overdamped** ($\\zeta > 1$): Slow exponential decay, no oscillation\n",
        "\n",
        "---\n"
    ]
})

# Cell 2: Imports
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from scipy.integrate import odeint\n",
        "from matplotlib.animation import FuncAnimation\n",
        "from IPython.display import HTML\n",
        "\n",
        "# Plot styling\n",
        "plt.rcParams['figure.figsize'] = (14, 8)\n",
        "plt.rcParams['font.size'] = 10\n",
        "\n",
        "print(\"Libraries imported successfully!\")\n",
        "print(\"  Ready for vibration analysis...\")\n"
    ]
})

# Cell 3: Theory - Undamped SDOF
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part A: Undamped Free Vibrations ($\\zeta = 0$)\n",
        "\n",
        "### System: Mass-Spring\n",
        "\n",
        "**Equation of motion**:\n",
        "$$m\\ddot{x} + kx = 0$$\n",
        "\n",
        "Divide by $m$:\n",
        "$$\\ddot{x} + \\omega_n^2 x = 0, \\quad \\omega_n = \\sqrt{\\frac{k}{m}}$$\n",
        "\n",
        "### Solution\n",
        "\n",
        "**General solution** (assume $x = e^{\\lambda t}$):\n",
        "$$\\lambda^2 + \\omega_n^2 = 0 \\quad \\Rightarrow \\quad \\lambda = \\pm i\\omega_n$$\n",
        "\n",
        "Real form:\n",
        "$$x(t) = A\\cos(\\omega_n t) + B\\sin(\\omega_n t)$$\n",
        "\n",
        "Or in amplitude-phase form:\n",
        "$$x(t) = X_0\\cos(\\omega_n t - \\phi)$$\n",
        "\n",
        "where:\n",
        "- $X_0 = \\sqrt{A^2 + B^2}$ → amplitude\n",
        "- $\\phi = \\arctan(B/A)$ → phase angle\n",
        "\n",
        "### Initial Conditions\n",
        "\n",
        "Given $x(0) = x_0$ and $\\dot{x}(0) = v_0$:\n",
        "$$A = x_0, \\quad B = \\frac{v_0}{\\omega_n}$$\n",
        "\n",
        "Therefore:\n",
        "$$x(t) = x_0\\cos(\\omega_n t) + \\frac{v_0}{\\omega_n}\\sin(\\omega_n t)$$\n",
        "\n",
        "### Key Properties\n",
        "\n",
        "**Frequency**:\n",
        "- Independent of amplitude (linear system)\n",
        "- Depends only on $k$ and $m$\n",
        "- $\\omega_n \\uparrow$ when $k \\uparrow$ (stiffer) or $m \\downarrow$ (lighter)\n",
        "\n",
        "**Period**: $T_n = \\frac{2\\pi}{\\omega_n} = 2\\pi\\sqrt{\\frac{m}{k}}$\n",
        "\n",
        "**Energy**: Conserved!\n",
        "$$E = \\frac{1}{2}kX_0^2 = KE + PE$$\n",
        "\n",
        "**Phase portrait**: Perfect circle (energy level curve)\n",
        "\n",
        "---\n"
    ]
})

# Cell 4: Example 1 - Undamped vibration
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 1: Undamped SDOF Vibration\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 1: Undamped Free Vibration\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "m = 2.0  # kg\n",
        "k = 200.0  # N/m\n",
        "c = 0.0  # N·s/m (no damping)\n",
        "\n",
        "# Calculate natural frequency\n",
        "omega_n = np.sqrt(k / m)\n",
        "f_n = omega_n / (2 * np.pi)\n",
        "T_n = 1 / f_n\n",
        "\n",
        "print(f\"\\nSystem Properties:\")\n",
        "print(f\"  Mass: {m} kg\")\n",
        "print(f\"  Stiffness: {k} N/m\")\n",
        "print(f\"  Damping: {c} N·s/m (undamped)\")\n",
        "\n",
        "print(f\"\\nNatural Frequency:\")\n",
        "print(f\"  ωₙ = {omega_n:.3f} rad/s\")\n",
        "print(f\"  fₙ = {f_n:.3f} Hz\")\n",
        "print(f\"  Tₙ = {T_n:.3f} s (period)\")\n",
        "\n",
        "# Initial conditions\n",
        "x0 = 0.1  # m (10 cm initial displacement)\n",
        "v0 = 0.0  # m/s (released from rest)\n",
        "\n",
        "print(f\"\\nInitial Conditions:\")\n",
        "print(f\"  x(0) = {x0*100} cm\")\n",
        "print(f\"  v(0) = {v0} m/s (released from rest)\")\n",
        "\n",
        "# ODE system\n",
        "def sdof_ode(y, t, m, c, k):\n",
        "    x, v = y\n",
        "    a = (-c * v - k * x) / m\n",
        "    return [v, a]\n",
        "\n",
        "# Time array\n",
        "t = np.linspace(0, 3*T_n, 1000)\n",
        "\n",
        "# Solve\n",
        "y0 = [x0, v0]\n",
        "solution = odeint(sdof_ode, y0, t, args=(m, c, k))\n",
        "x = solution[:, 0]\n",
        "v = solution[:, 1]\n",
        "\n",
        "# Energy\n",
        "KE = 0.5 * m * v**2\n",
        "PE = 0.5 * k * x**2\n",
        "E_total = KE + PE\n",
        "\n",
        "# Analytical solution for comparison\n",
        "A = x0\n",
        "B = v0 / omega_n\n",
        "X0 = np.sqrt(A**2 + B**2)\n",
        "x_analytical = x0 * np.cos(omega_n * t) + (v0 / omega_n) * np.sin(omega_n * t)\n",
        "\n",
        "# Plotting\n",
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
        "\n",
        "# Displacement vs time\n",
        "ax1 = axes[0, 0]\n",
        "ax1.plot(t, x*100, 'b-', linewidth=2, label='Numerical')\n",
        "ax1.plot(t, x_analytical*100, 'r--', linewidth=1.5, alpha=0.7, label='Analytical')\n",
        "ax1.axhline(y=0, color='k', linestyle='-', alpha=0.3)\n",
        "ax1.set_xlabel('Time (s)', fontsize=11)\n",
        "ax1.set_ylabel('Displacement (cm)', fontsize=11)\n",
        "ax1.set_title(f'Displacement vs Time (ωₙ = {omega_n:.2f} rad/s)', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=10)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Phase portrait\n",
        "ax2 = axes[0, 1]\n",
        "ax2.plot(x*100, v*100, 'b-', linewidth=2)\n",
        "ax2.plot(x[0]*100, v[0]*100, 'go', markersize=10, label='Start')\n",
        "ax2.set_xlabel('Displacement (cm)', fontsize=11)\n",
        "ax2.set_ylabel('Velocity (cm/s)', fontsize=11)\n",
        "ax2.set_title('Phase Portrait (Perfect Circle!)', fontsize=12, fontweight='bold')\n",
        "ax2.legend(fontsize=10)\n",
        "ax2.grid(True, alpha=0.3)\n",
        "ax2.set_aspect('equal', adjustable='box')\n",
        "\n",
        "# Energy\n",
        "ax3 = axes[1, 0]\n",
        "ax3.plot(t, KE, 'b-', linewidth=2, label='Kinetic')\n",
        "ax3.plot(t, PE, 'r-', linewidth=2, label='Potential')\n",
        "ax3.plot(t, E_total, 'k--', linewidth=2, label='Total')\n",
        "ax3.set_xlabel('Time (s)', fontsize=11)\n",
        "ax3.set_ylabel('Energy (J)', fontsize=11)\n",
        "ax3.set_title('Energy (Conserved!)', fontsize=12, fontweight='bold')\n",
        "ax3.legend(fontsize=10)\n",
        "ax3.grid(True, alpha=0.3)\n",
        "\n",
        "# Velocity vs time\n",
        "ax4 = axes[1, 1]\n",
        "ax4.plot(t, v*100, 'b-', linewidth=2)\n",
        "ax4.axhline(y=0, color='k', linestyle='-', alpha=0.3)\n",
        "ax4.set_xlabel('Time (s)', fontsize=11)\n",
        "ax4.set_ylabel('Velocity (cm/s)', fontsize=11)\n",
        "ax4.set_title('Velocity vs Time', fontsize=12, fontweight='bold')\n",
        "ax4.grid(True, alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f\"\\nAnalysis complete!\")\n",
        "print(f\"\\nKey observations:\")\n",
        "print(f\"  1. Oscillates forever (no energy loss)\")\n",
        "print(f\"  2. Period Tₙ = {T_n:.3f}s is constant\")\n",
        "print(f\"  3. Energy conserved: E = {E_total[0]:.6f} J\")\n",
        "print(f\"  4. Phase portrait is perfect circle (no spiraling)\")\n",
        "print(f\"  5. Amplitude X₀ = {X0*100:.2f} cm (constant)\")\n"
    ]
})

# Cell 5: Theory - Damped SDOF
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part B: Damped Free Vibrations ($\\zeta > 0$)\n",
        "\n",
        "### Equation with Damping\n",
        "\n",
        "$$m\\ddot{x} + c\\dot{x} + kx = 0$$\n",
        "\n",
        "Standard form:\n",
        "$$\\ddot{x} + 2\\zeta\\omega_n\\dot{x} + \\omega_n^2 x = 0$$\n",
        "\n",
        "where:\n",
        "- $\\omega_n = \\sqrt{k/m}$ → undamped natural frequency\n",
        "- $\\zeta = \\frac{c}{2\\sqrt{km}} = \\frac{c}{c_c}$ → damping ratio\n",
        "- $c_c = 2\\sqrt{km} = 2m\\omega_n$ → critical damping coefficient\n",
        "\n",
        "### Solution (assume $x = e^{\\lambda t}$)\n",
        "\n",
        "Characteristic equation:\n",
        "$$\\lambda^2 + 2\\zeta\\omega_n\\lambda + \\omega_n^2 = 0$$\n",
        "\n",
        "Roots:\n",
        "$$\\lambda = -\\zeta\\omega_n \\pm \\omega_n\\sqrt{\\zeta^2 - 1}$$\n",
        "\n",
        "### Three Cases\n",
        "\n",
        "#### 1. Underdamped ($\\zeta < 1$)\n",
        "\n",
        "**Roots**: Complex conjugates $\\lambda = -\\zeta\\omega_n \\pm i\\omega_d$\n",
        "\n",
        "where $\\omega_d = \\omega_n\\sqrt{1 - \\zeta^2}$ → **damped frequency**\n",
        "\n",
        "**Solution**:\n",
        "$$x(t) = X_0 e^{-\\zeta\\omega_n t}\\cos(\\omega_d t - \\phi)$$\n",
        "\n",
        "**Characteristics**:\n",
        "- Oscillates with **exponentially decaying envelope**\n",
        "- Frequency $\\omega_d < \\omega_n$ (damping slows oscillation)\n",
        "- **Logarithmic decrement**: $\\delta = \\ln\\frac{x_n}{x_{n+1}} = \\frac{2\\pi\\zeta}{\\sqrt{1-\\zeta^2}}$\n",
        "\n",
        "#### 2. Critically Damped ($\\zeta = 1$)\n",
        "\n",
        "**Roots**: Real, repeated $\\lambda = -\\omega_n$\n",
        "\n",
        "**Solution**:\n",
        "$$x(t) = (A + Bt)e^{-\\omega_n t}$$\n",
        "\n",
        "**Characteristics**:\n",
        "- **Fastest return** to equilibrium without overshoot\n",
        "- No oscillation\n",
        "- Used in: door closers, automotive dampers\n",
        "\n",
        "#### 3. Overdamped ($\\zeta > 1$)\n",
        "\n",
        "**Roots**: Real, distinct $\\lambda_1, \\lambda_2 < 0$\n",
        "\n",
        "**Solution**:\n",
        "$$x(t) = A e^{\\lambda_1 t} + B e^{\\lambda_2 t}$$\n",
        "\n",
        "**Characteristics**:\n",
        "- **Slow exponential decay**\n",
        "- No oscillation (over-damped)\n",
        "- Slower than critical damping\n",
        "\n",
        "### Logarithmic Decrement\n",
        "\n",
        "For underdamped systems, measure decay:\n",
        "\n",
        "$$\\delta = \\ln\\frac{x_n}{x_{n+1}} = \\frac{2\\pi\\zeta}{\\sqrt{1-\\zeta^2}} \\approx 2\\pi\\zeta \\quad (\\text{for } \\zeta \\ll 1)$$\n",
        "\n",
        "Invert to find damping:\n",
        "$$\\zeta = \\frac{\\delta}{\\sqrt{4\\pi^2 + \\delta^2}}$$\n",
        "\n",
        "**Experimental use**: Measure successive peak amplitudes to extract $\\zeta$!\n",
        "\n",
        "---\n"
    ]
})

# Cell 6: Example 2 - Three damping regimes
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 2: Three Damping Regimes\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 2: Comparison of Damping Regimes\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Same system as before\n",
        "m = 2.0  # kg\n",
        "k = 200.0  # N/m\n",
        "omega_n = np.sqrt(k / m)\n",
        "c_critical = 2 * np.sqrt(k * m)  # Critical damping\n",
        "\n",
        "print(f\"\\nSystem Properties:\")\n",
        "print(f\"  m = {m} kg, k = {k} N/m\")\n",
        "print(f\"  ωₙ = {omega_n:.3f} rad/s\")\n",
        "print(f\"  c_critical = {c_critical:.3f} N·s/m\")\n",
        "\n",
        "# Three cases\n",
        "zeta_values = [0.1, 1.0, 2.0]  # Underdamped, critical, overdamped\n",
        "c_values = [zeta * c_critical for zeta in zeta_values]\n",
        "labels = ['Underdamped (ζ=0.1)', 'Critically Damped (ζ=1.0)', 'Overdamped (ζ=2.0)']\n",
        "colors = ['blue', 'green', 'red']\n",
        "\n",
        "print(f\"\\nDamping Cases:\")\n",
        "for i, (zeta, c) in enumerate(zip(zeta_values, c_values)):\n",
        "    print(f\"  {labels[i]}: c = {c:.3f} N·s/m\")\n",
        "\n",
        "# Initial conditions (same for all)\n",
        "x0 = 0.1  # m\n",
        "v0 = 0.0  # m/s\n",
        "\n",
        "# Time array\n",
        "t = np.linspace(0, 5, 1000)\n",
        "\n",
        "# Solve for all three cases\n",
        "solutions = []\n",
        "for c in c_values:\n",
        "    sol = odeint(sdof_ode, [x0, v0], t, args=(m, c, k))\n",
        "    solutions.append(sol)\n",
        "\n",
        "# Plotting\n",
        "fig, axes = plt.subplots(2, 3, figsize=(16, 10))\n",
        "\n",
        "# Row 1: Time histories\n",
        "for i, (sol, label, color) in enumerate(zip(solutions, labels, colors)):\n",
        "    ax = axes[0, i]\n",
        "    x = sol[:, 0]\n",
        "    ax.plot(t, x*100, color=color, linewidth=2)\n",
        "    ax.axhline(y=0, color='k', linestyle='--', alpha=0.3)\n",
        "    \n",
        "    # Add envelope for underdamped\n",
        "    if i == 0:\n",
        "        zeta = zeta_values[i]\n",
        "        envelope = x0 * 100 * np.exp(-zeta * omega_n * t)\n",
        "        ax.plot(t, envelope, 'k--', linewidth=1, alpha=0.5, label='Envelope')\n",
        "        ax.plot(t, -envelope, 'k--', linewidth=1, alpha=0.5)\n",
        "        ax.legend(fontsize=9)\n",
        "    \n",
        "    ax.set_xlabel('Time (s)', fontsize=10)\n",
        "    ax.set_ylabel('Displacement (cm)', fontsize=10)\n",
        "    ax.set_title(label, fontsize=11, fontweight='bold')\n",
        "    ax.grid(True, alpha=0.3)\n",
        "\n",
        "# Row 2: Phase portraits\n",
        "for i, (sol, label, color) in enumerate(zip(solutions, labels, colors)):\n",
        "    ax = axes[1, i]\n",
        "    x = sol[:, 0]\n",
        "    v = sol[:, 1]\n",
        "    ax.plot(x*100, v*100, color=color, linewidth=2)\n",
        "    ax.plot(x[0]*100, v[0]*100, 'go', markersize=10, label='Start')\n",
        "    ax.plot(0, 0, 'ko', markersize=8, label='Equilibrium')\n",
        "    ax.set_xlabel('Displacement (cm)', fontsize=10)\n",
        "    ax.set_ylabel('Velocity (cm/s)', fontsize=10)\n",
        "    ax.set_title(f'Phase Portrait: {label}', fontsize=11, fontweight='bold')\n",
        "    ax.legend(fontsize=9)\n",
        "    ax.grid(True, alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Calculate damped frequency and logarithmic decrement for underdamped\n",
        "zeta_under = zeta_values[0]\n",
        "omega_d = omega_n * np.sqrt(1 - zeta_under**2)\n",
        "T_d = 2 * np.pi / omega_d\n",
        "log_dec = 2 * np.pi * zeta_under / np.sqrt(1 - zeta_under**2)\n",
        "\n",
        "print(f\"\\nUnderdamped System (ζ = {zeta_under}):\")\n",
        "print(f\"  Damped frequency: ωd = {omega_d:.3f} rad/s\")\n",
        "print(f\"  Damped period: Td = {T_d:.3f} s\")\n",
        "print(f\"  Logarithmic decrement: δ = {log_dec:.4f}\")\n",
        "\n",
        "# Verify log decrement from simulation\n",
        "x_under = solutions[0][:, 0]\n",
        "# Find peaks\n",
        "from scipy.signal import find_peaks\n",
        "peaks, _ = find_peaks(x_under)\n",
        "if len(peaks) >= 2:\n",
        "    measured_delta = np.log(x_under[peaks[0]] / x_under[peaks[1]])\n",
        "    print(f\"  Measured δ from peaks: {measured_delta:.4f} (should match theory!)\")\n",
        "\n",
        "print(f\"\\nKey observations:\")\n",
        "print(f\"  1. Underdamped: Oscillates + decays (spiral inward)\")\n",
        "print(f\"  2. Critical: Fastest return, no overshoot\")\n",
        "print(f\"  3. Overdamped: Slow, no oscillation\")\n",
        "print(f\"  4. Phase portraits show energy dissipation (spiral to origin)\")\n"
    ]
})

# Cell 7: Example 3 - Experimental parameter extraction
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 3: Experimental Modal Parameter Extraction\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 3: Extract Modal Parameters from Measurement\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "print(\"\\nScenario: Unknown system, we measured free response\")\n",
        "print(\"   Goal: Find ωₙ and ζ from time-series data\")\n",
        "\n",
        "# \"Unknown\" system (we'll pretend we measured this)\n",
        "m_actual = 1.5  # kg (unknown to us)\n",
        "k_actual = 150.0  # N/m (unknown to us)\n",
        "zeta_actual = 0.15  # (unknown to us)\n",
        "c_actual = zeta_actual * 2 * np.sqrt(k_actual * m_actual)\n",
        "\n",
        "omega_n_actual = np.sqrt(k_actual / m_actual)\n",
        "\n",
        "print(f\"\\n(Hidden) Actual System:\")\n",
        "print(f\"   m = {m_actual} kg, k = {k_actual} N/m\")\n",
        "print(f\"   ζ_actual = {zeta_actual}\")\n",
        "print(f\"   ωₙ_actual = {omega_n_actual:.3f} rad/s\")\n",
        "\n",
        "# Generate \"measurement\" data\n",
        "x0_meas = 0.05  # m\n",
        "v0_meas = 0.0\n",
        "t_meas = np.linspace(0, 5, 500)\n",
        "sol_meas = odeint(sdof_ode, [x0_meas, v0_meas], t_meas, args=(m_actual, c_actual, k_actual))\n",
        "x_meas = sol_meas[:, 0]\n",
        "\n",
        "# Add some noise to simulate real measurement\n",
        "np.random.seed(42)\n",
        "noise = 0.001 * np.random.randn(len(x_meas))  # 1mm noise\n",
        "x_meas_noisy = x_meas + noise\n",
        "\n",
        "print(f\"\\nWe measured vibration for {t_meas[-1]} seconds\")\n",
        "print(f\"   Initial displacement: {x0_meas*100:.1f} cm\")\n",
        "print(f\"   Measurement noise: ~1 mm RMS\")\n",
        "\n",
        "# Method 1: Extract natural frequency from zero-crossings or peaks\n",
        "from scipy.signal import find_peaks\n",
        "peaks, _ = find_peaks(x_meas_noisy)\n",
        "peak_times = t_meas[peaks]\n",
        "peak_values = x_meas_noisy[peaks]\n",
        "\n",
        "if len(peaks) >= 3:\n",
        "    # Average period from peaks\n",
        "    periods = np.diff(peak_times)\n",
        "    T_d_measured = np.mean(periods)\n",
        "    omega_d_measured = 2 * np.pi / T_d_measured\n",
        "    \n",
        "    print(f\"\\nStep 1: Measure damped frequency\")\n",
        "    print(f\"   Found {len(peaks)} peaks\")\n",
        "    print(f\"   Average period: Td = {T_d_measured:.4f} s\")\n",
        "    print(f\"   Damped frequency: ωd = {omega_d_measured:.3f} rad/s\")\n",
        "\n",
        "# Method 2: Logarithmic decrement from peak decay\n",
        "if len(peaks) >= 2:\n",
        "    # Calculate log dec from multiple consecutive peaks\n",
        "    deltas = []\n",
        "    for i in range(len(peaks)-1):\n",
        "        delta_i = np.log(peak_values[i] / peak_values[i+1])\n",
        "        deltas.append(delta_i)\n",
        "    \n",
        "    delta_measured = np.mean(deltas)\n",
        "    \n",
        "    # Extract damping ratio from log dec\n",
        "    zeta_measured = delta_measured / np.sqrt(4*np.pi**2 + delta_measured**2)\n",
        "    \n",
        "    print(f\"\\nStep 2: Measure logarithmic decrement\")\n",
        "    print(f\"   Average δ = {delta_measured:.4f}\")\n",
        "    print(f\"   Extracted ζ = {zeta_measured:.4f}\")\n",
        "\n",
        "# Method 3: Calculate undamped natural frequency\n",
        "omega_n_measured = omega_d_measured / np.sqrt(1 - zeta_measured**2)\n",
        "f_n_measured = omega_n_measured / (2 * np.pi)\n",
        "\n",
        "print(f\"\\nStep 3: Calculate undamped natural frequency\")\n",
        "print(f\"   ωₙ = ωd / √(1-ζ²) = {omega_n_measured:.3f} rad/s\")\n",
        "print(f\"   fₙ = {f_n_measured:.3f} Hz\")\n",
        "\n",
        "# Plotting\n",
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "# Measured data with identified peaks\n",
        "ax1 = axes[0]\n",
        "ax1.plot(t_meas, x_meas_noisy*100, 'b-', linewidth=1, alpha=0.7, label='Measured data')\n",
        "ax1.plot(peak_times, peak_values*100, 'ro', markersize=8, label=f'Peaks (n={len(peaks)})')\n",
        "\n",
        "# Fitted envelope\n",
        "envelope_fit = x0_meas * 100 * np.exp(-zeta_measured * omega_n_measured * t_meas)\n",
        "ax1.plot(t_meas, envelope_fit, 'k--', linewidth=2, alpha=0.6, label='Fitted envelope')\n",
        "ax1.plot(t_meas, -envelope_fit, 'k--', linewidth=2, alpha=0.6)\n",
        "\n",
        "ax1.axhline(y=0, color='k', linestyle='-', alpha=0.3)\n",
        "ax1.set_xlabel('Time (s)', fontsize=11)\n",
        "ax1.set_ylabel('Displacement (cm)', fontsize=11)\n",
        "ax1.set_title('Measured Response + Identified Parameters', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=10)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Verification: compare with actual\n",
        "ax2 = axes[1]\n",
        "params = ['ωₙ (rad/s)', 'ζ', 'fₙ (Hz)']\n",
        "actual_vals = [omega_n_actual, zeta_actual, omega_n_actual/(2*np.pi)]\n",
        "measured_vals = [omega_n_measured, zeta_measured, f_n_measured]\n",
        "errors = [abs(m-a)/a*100 for m, a in zip(measured_vals, actual_vals)]\n",
        "\n",
        "x_pos = np.arange(len(params))\n",
        "width = 0.35\n",
        "\n",
        "ax2.bar(x_pos - width/2, actual_vals, width, label='Actual', color='green', alpha=0.7)\n",
        "ax2.bar(x_pos + width/2, measured_vals, width, label='Measured', color='blue', alpha=0.7)\n",
        "\n",
        "ax2.set_ylabel('Value', fontsize=11)\n",
        "ax2.set_title('Parameter Extraction Accuracy', fontsize=12, fontweight='bold')\n",
        "ax2.set_xticks(x_pos)\n",
        "ax2.set_xticklabels(params, fontsize=10)\n",
        "ax2.legend(fontsize=10)\n",
        "ax2.grid(True, alpha=0.3, axis='y')\n",
        "\n",
        "# Add error text\n",
        "for i, (a, m, e) in enumerate(zip(actual_vals, measured_vals, errors)):\n",
        "    ax2.text(i, max(a, m)*1.05, f'Error: {e:.2f}%', ha='center', fontsize=9)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f\"\\nVerification:\")\n",
        "print(f\"   Parameter      Actual      Measured    Error\")\n",
        "print(f\"   ωₙ (rad/s)     {omega_n_actual:.3f}       {omega_n_measured:.3f}       {errors[0]:.2f}%\")\n",
        "print(f\"   ζ              {zeta_actual:.4f}      {zeta_measured:.4f}      {errors[1]:.2f}%\")\n",
        "print(f\"   fₙ (Hz)        {actual_vals[2]:.3f}       {measured_vals[2]:.3f}       {errors[2]:.2f}%\")\n",
        "\n",
        "print(f\"\\nThis is how modal testing works in practice!\")\n",
        "print(f\"   1. Impact structure (hammer test)\")\n",
        "print(f\"   2. Measure free response (accelerometer)\")\n",
        "print(f\"   3. Extract ωₙ and ζ from decay\")\n",
        "print(f\"   4. Build mathematical model\")\n"
    ]
})

# Cell 8: Summary
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Summary\n",
        "\n",
        "### Key Equations\n",
        "\n",
        "**Equation of motion**:\n",
        "$$m\\ddot{x} + c\\dot{x} + kx = 0 \\quad \\Rightarrow \\quad \\ddot{x} + 2\\zeta\\omega_n\\dot{x} + \\omega_n^2 x = 0$$\n",
        "\n",
        "**Natural frequency**:\n",
        "$$\\omega_n = \\sqrt{\\frac{k}{m}}, \\quad f_n = \\frac{\\omega_n}{2\\pi}, \\quad T_n = \\frac{1}{f_n}$$\n",
        "\n",
        "**Damping ratio**:\n",
        "$$\\zeta = \\frac{c}{c_c} = \\frac{c}{2\\sqrt{km}} = \\frac{c}{2m\\omega_n}$$\n",
        "\n",
        "**Damped frequency** (underdamped):\n",
        "$$\\omega_d = \\omega_n\\sqrt{1 - \\zeta^2}$$\n",
        "\n",
        "**Logarithmic decrement**:\n",
        "$$\\delta = \\ln\\frac{x_n}{x_{n+1}} = \\frac{2\\pi\\zeta}{\\sqrt{1-\\zeta^2}} \\quad \\Rightarrow \\quad \\zeta = \\frac{\\delta}{\\sqrt{4\\pi^2 + \\delta^2}}$$\n",
        "\n",
        "### Three Damping Regimes\n",
        "\n",
        "| Regime | Condition | Behavior | Application |\n",
        "|--------|-----------|----------|-------------|\n",
        "| **Underdamped** | $\\zeta < 1$ | Oscillates with decay | Musical instruments, sensors |\n",
        "| **Critically Damped** | $\\zeta = 1$ | Fastest return, no overshoot | Door closers, dampers |\n",
        "| **Overdamped** | $\\zeta > 1$ | Slow decay, no oscillation | Heavy damping systems |\n",
        "\n",
        "### Experimental Modal Analysis\n",
        "\n",
        "**From free response measurements**:\n",
        "1. **Period measurement**: Count peaks → $T_d$ → $\\omega_d = 2\\pi/T_d$\n",
        "2. **Amplitude decay**: Measure peak amplitudes → $\\delta = \\ln(x_n/x_{n+1})$ → $\\zeta$\n",
        "3. **Natural frequency**: $\\omega_n = \\omega_d / \\sqrt{1-\\zeta^2}$\n",
        "\n",
        "**Tools**:\n",
        "- Accelerometer for vibration measurement\n",
        "- Impact hammer for excitation\n",
        "- FFT for frequency domain analysis\n",
        "\n",
        "### Design Guidelines\n",
        "\n",
        "**Natural frequency**:\n",
        "- Increase $k$ (stiffer) → $\\omega_n \\uparrow$\n",
        "- Decrease $m$ (lighter) → $\\omega_n \\uparrow$\n",
        "- Want $\\omega_n$ far from forcing frequencies (avoid resonance!)\n",
        "\n",
        "**Damping**:\n",
        "- $\\zeta < 0.05$: Very lightly damped (many oscillations)\n",
        "- $0.05 < \\zeta < 0.3$: Light damping (typical for structures)\n",
        "- $\\zeta \\approx 0.7$: Good compromise (overshoot ~5%)\n",
        "- $\\zeta = 1.0$: Critical damping (optimal for settling time)\n",
        "- $\\zeta > 1.0$: Overdamped (sluggish response)\n",
        "\n",
        "### Connection to Multi-DOF\n",
        "\n",
        "**Each mode of multi-DOF system behaves as SDOF**!\n",
        "\n",
        "For mode $i$:\n",
        "- Natural frequency: $\\omega_i$\n",
        "- Mode shape: $\\phi_i$\n",
        "- Damping ratio: $\\zeta_i$\n",
        "\n",
        "Total response = sum of modal responses (next lecture!)\n",
        "\n",
        "### What's Next?\n",
        "\n",
        "**Unit 5 Lecture 5**: MDOF Modal Analysis\n",
        "- Modal decomposition\n",
        "- Mode superposition\n",
        "- Forced response\n",
        "- Frequency response functions (FRF)\n",
        "\n",
        "---\n",
        "\n",
        "### Practice Problems\n",
        "\n",
        "1. **Design problem**: Cantilever beam, L=1m, E=70GPa, I=10⁻⁶m⁴, tip mass m=0.5kg. Find $\\omega_n$.\n",
        "2. **Decay analysis**: System oscillates 10 times before amplitude drops to 10%. Find $\\zeta$.\n",
        "3. **Critically damped**: Given m=2kg, k=800N/m, find $c$ for critical damping.\n",
        "4. **Phase lag**: For underdamped system with $\\zeta=0.2$, what is phase between displacement and velocity?\n",
        "\n",
        "---\n"
    ]
})

# Save notebook
os.makedirs(output_dir, exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("=" * 60)
print("Unit 5 Lecture 4 Created Successfully!")
print("=" * 60)
print(f"\nFile: {output_path}")
print(f"\nNotebook structure:")
print(f"Total cells: {len(notebook['cells'])}")
print(f"Markdown: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'markdown')}")
print(f"Code: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'code')}")
print(f"\nContent:")
print(f"Part A: Undamped free vibrations (ωₙ = √(k/m))")
print(f"Part B: Damped vibrations (three regimes)")
print(f"Example 3: Modal parameter extraction (experimental)")
print(f"\nDuration: ~90 minutes")
print(f"\nReady to test!")
