"""
Create Unit 5 Lecture 1: Equations of Motion for Rigid Bodies
Focus: Translation + Rotation, Moment of Inertia, τ = I·α
Target: ~90 minutes comprehensive coverage
"""

import json
import os

# Paths
output_dir = r"d:\Sunny\DSM\notebooks\Teacher"
output_path = os.path.join(output_dir, "T_U5_L1_Rigid_Body_Equations_of_Motion.ipynb")

# Create notebook structure
notebook = {
    "cells": [],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.14.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

# Cell 1: Header
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# Unit 5 Lecture 1: Equations of Motion for Rigid Bodies\n",
        "## Translation + Rotation Dynamics\n",
        "\n",
        "---\n",
        "\n",
        "### Learning Objectives\n",
        "By the end of this lecture, you will be able to:\n",
        "1. **Derive equations of motion** for rigid bodies (translation + rotation)\n",
        "2. **Apply Newton's laws** to combined translational and rotational motion\n",
        "3. **Calculate moment of inertia** for common shapes and use parallel axis theorem\n",
        "4. **Solve rolling problems** using τ = I·α and constraint equations\n",
        "5. **Analyze 1-DOF rigid body systems** (pendulums, rolling objects, rotating disks)\n",
        "\n",
        "### Context\n",
        "**From particle kinetics to rigid body kinetics:**\n",
        "- Unit 4: Particles (point masses, no rotation) → ΣF = ma\n",
        "- **This unit**: Rigid bodies (extended objects, rotation matters) → ΣF = ma **AND** Στ = I·α\n",
        "\n",
        "**Why does rotation matter?**\n",
        "- Wheels, gears, robots, spacecraft: rotation is fundamental\n",
        "- Energy: rotation contributes ½Iω² (not just ½mv²)\n",
        "- Design: moment of inertia affects response (flywheel, gyroscope)\n",
        "\n",
        "### Key Equations Preview\n",
        "$$\\boxed{\\sum \\mathbf{F} = m \\mathbf{a}_{cm}} \\quad \\text{(Translation)}$$\n",
        "$$\\boxed{\\sum \\tau = I \\alpha} \\quad \\text{(Rotation about CM or fixed axis)}$$\n",
        "\n",
        "**Rolling constraint**: $v_{cm} = \\omega R$ (no slip)\n",
        "\n",
        "---\n"
    ]
})

# Cell 2: Imports
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Import libraries\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from matplotlib.animation import FuncAnimation\n",
        "from mpl_toolkits.mplot3d import Axes3D\n",
        "from scipy.integrate import odeint\n",
        "import sympy as sp\n",
        "\n",
        "# Plotting style\n",
        "plt.style.use('seaborn-v0_8-darkgrid')\n",
        "plt.rcParams['figure.figsize'] = (12, 4)\n",
        "\n",
        "print(\"Libraries imported successfully!\")\n",
        "print(\"  Ready to analyze rigid body dynamics...\")\n"
    ]
})

# Cell 3: Part A - Theory
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part A: Rigid Body Equations of Motion \n",
        "\n",
        "### What is a Rigid Body?\n",
        "**Definition**: An extended object where distances between all points remain constant\n",
        "- **Idealization**: No deformation (perfectly stiff)\n",
        "- **Reality**: Steel beam, wheel, robot link → nearly rigid\n",
        "- **Not rigid**: Spring, rope, fluid\n",
        "\n",
        "### Two Types of Motion\n",
        "\n",
        "#### 1. Translation (ΣF = m·a_cm)\n",
        "Every point has the **same velocity**:\n",
        "$$\\mathbf{v}_P = \\mathbf{v}_{cm} \\quad \\text{(for all points P)}$$\n",
        "\n",
        "**Newton's 2nd Law for CM**:\n",
        "$$\\sum \\mathbf{F}_{\\text{external}} = m \\mathbf{a}_{cm}$$\n",
        "\n",
        "**Key insight**: Center of mass moves like a particle with total mass!\n",
        "\n",
        "#### 2. Rotation (Στ = I·α)\n",
        "Object spins about an axis. Each point has different velocity!\n",
        "\n",
        "**Velocity of point P on rigid body**:\n",
        "$$\\mathbf{v}_P = \\mathbf{v}_{cm} + \\boldsymbol{\\omega} \\times \\mathbf{r}_{P/cm}$$\n",
        "\n",
        "where:\n",
        "- $\\boldsymbol{\\omega}$ = angular velocity vector (rad/s)\n",
        "- $\\mathbf{r}_{P/cm}$ = position of P relative to CM\n",
        "\n",
        "**Angular Equation of Motion** (about CM or fixed axis):\n",
        "$$\\sum \\tau = I \\alpha$$\n",
        "\n",
        "where:\n",
        "- $\\tau$ = torque (N·m)\n",
        "- $I$ = moment of inertia (kg·m²) — **resistance to rotation**\n",
        "- $\\alpha = \\dot{\\omega}$ = angular acceleration (rad/s²)\n",
        "\n",
        "### Moment of Inertia\n",
        "**Definition**: How mass is distributed about rotation axis\n",
        "$$I = \\int r^2 \\, dm = \\sum m_i r_i^2$$\n",
        "\n",
        "**Common Shapes** (about center):\n",
        "- **Point mass**: $I = m r^2$\n",
        "- **Thin rod** (length L, mass m, about center): $I = \\frac{1}{12} m L^2$\n",
        "- **Solid disk/cylinder** (radius R): $I = \\frac{1}{2} m R^2$\n",
        "- **Hollow cylinder** (radius R): $I = m R^2$\n",
        "- **Solid sphere**: $I = \\frac{2}{5} m R^2$\n",
        "\n",
        "**Parallel Axis Theorem**: Shift axis from CM to distance $d$ away\n",
        "$$I_{\\text{new}} = I_{cm} + m d^2$$\n",
        "\n",
        "### Combined Motion: Rolling\n",
        "**Rolling without slipping**: Point at contact has zero velocity!\n",
        "$$v_{cm} = \\omega R \\quad \\text{(constraint)}$$\n",
        "\n",
        "**Consequences**:\n",
        "- Acceleration: $a_{cm} = \\alpha R$\n",
        "- Total kinetic energy: $KE = \\frac{1}{2} m v_{cm}^2 + \\frac{1}{2} I_{cm} \\omega^2$\n",
        "\n",
        "---\n"
    ]
})

# Cell 4: Example - Calculate Moment of Inertia
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 1: Moment of Inertia Calculations\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 1: Moment of Inertia for Common Shapes\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "m = 5.0  # kg\n",
        "R = 0.2  # m (radius for disk/sphere)\n",
        "L = 1.0  # m (length for rod)\n",
        "\n",
        "# Calculate moments of inertia\n",
        "I_point = m * R**2\n",
        "I_rod_center = (1/12) * m * L**2\n",
        "I_rod_end = (1/3) * m * L**2  # Using parallel axis theorem\n",
        "I_disk = (1/2) * m * R**2\n",
        "I_hollow_cyl = m * R**2\n",
        "I_sphere = (2/5) * m * R**2\n",
        "\n",
        "print(f\"\\nMass: {m} kg\")\n",
        "print(f\"Radius (disk/sphere): {R} m\")\n",
        "print(f\"Length (rod): {L} m\")\n",
        "print(f\"\\nMoments of Inertia (kg·m²):\")\n",
        "print(f\"  Point mass at distance R:     {I_point:.4f}\")\n",
        "print(f\"  Rod (about center):           {I_rod_center:.4f}\")\n",
        "print(f\"  Rod (about end):              {I_rod_end:.4f}\")\n",
        "print(f\"  Solid disk:                   {I_disk:.4f}\")\n",
        "print(f\"  Hollow cylinder:              {I_hollow_cyl:.4f}\")\n",
        "print(f\"  Solid sphere:                 {I_sphere:.4f}\")\n",
        "\n",
        "# Verify parallel axis theorem for rod\n",
        "d = L / 2  # Distance from center to end\n",
        "I_rod_end_check = I_rod_center + m * d**2\n",
        "print(f\"\\nParallel Axis Theorem Check:\")\n",
        "print(f\"  Rod about end (formula): {I_rod_end:.4f} kg·m²\")\n",
        "print(f\"  Rod about end (PAT):     {I_rod_end_check:.4f} kg·m² \")\n",
        "\n",
        "# Visualize distribution\n",
        "fig, ax = plt.subplots(figsize=(10, 6))\n",
        "\n",
        "shapes = ['Point mass', 'Rod\\n(center)', 'Rod\\n(end)', 'Solid\\ndisk', 'Hollow\\ncyl', 'Solid\\nsphere']\n",
        "inertias = [I_point, I_rod_center, I_rod_end, I_disk, I_hollow_cyl, I_sphere]\n",
        "colors = ['red', 'blue', 'darkblue', 'green', 'darkgreen', 'purple']\n",
        "\n",
        "bars = ax.bar(shapes, inertias, color=colors, alpha=0.7, edgecolor='black', linewidth=2)\n",
        "ax.set_ylabel('Moment of Inertia (kg·m²)', fontsize=12, fontweight='bold')\n",
        "ax.set_title(f'Moment of Inertia Comparison (m={m} kg)', fontsize=14, fontweight='bold')\n",
        "ax.grid(axis='y', alpha=0.3)\n",
        "\n",
        "# Add values on bars\n",
        "for bar, val in zip(bars, inertias):\n",
        "    height = bar.get_height()\n",
        "    ax.text(bar.get_x() + bar.get_width()/2, height + 0.002,\n",
        "            f'{val:.4f}', ha='center', va='bottom', fontsize=10, fontweight='bold')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\nInsight: Hollow cylinder has largest I (mass farthest from axis)\")\n",
        "print(\"            Solid sphere has smallest I (mass closer to axis)\")\n"
    ]
})

# Cell 5: Rolling Down Incline Theory
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part B: Rolling Motion Analysis \n",
        "\n",
        "### Classic Problem: Rolling Down an Incline\n",
        "\n",
        "**Setup**: Object (mass m, radius R, moment of inertia I) rolls down incline (angle θ)\n",
        "\n",
        "**Forces**:\n",
        "- Weight: $mg$ (down)\n",
        "- Normal: $N$ (perpendicular to incline)\n",
        "- Friction: $f$ (up the incline) — **provides torque for rotation!**\n",
        "\n",
        "**Equations**:\n",
        "\n",
        "**Translation** (down incline, +x direction):\n",
        "$$m a_{cm} = mg \\sin\\theta - f$$\n",
        "\n",
        "**Rotation** (about center of mass):\n",
        "$$I \\alpha = f R$$\n",
        "\n",
        "**Rolling constraint** (no slip):\n",
        "$$a_{cm} = \\alpha R$$\n",
        "\n",
        "### Solution Strategy\n",
        "1. Use constraint to eliminate $\\alpha$: $\\alpha = a_{cm}/R$\n",
        "2. From rotation equation: $f = I \\alpha / R = I a_{cm} / R^2$\n",
        "3. Substitute into translation equation:\n",
        "   $$m a_{cm} = mg \\sin\\theta - \\frac{I a_{cm}}{R^2}$$\n",
        "4. Solve for $a_{cm}$:\n",
        "   $$\\boxed{a_{cm} = \\frac{g \\sin\\theta}{1 + I/(mR^2)}}$$\n",
        "\n",
        "### Key Results\n",
        "\n",
        "**Define**: $\\beta = I/(mR^2)$ (dimensionless shape factor)\n",
        "- Solid sphere: $\\beta = 2/5$\n",
        "- Solid disk: $\\beta = 1/2$\n",
        "- Hollow cylinder: $\\beta = 1$\n",
        "\n",
        "**Acceleration**:\n",
        "$$a_{cm} = \\frac{g \\sin\\theta}{1 + \\beta}$$\n",
        "\n",
        "**Who wins the race down the incline?**\n",
        "- **Smallest $\\beta$ → fastest** (less rotational inertia)\n",
        "- Order: Solid sphere > Solid disk > Hollow cylinder\n",
        "- **Independent of mass and radius!** (shape only)\n",
        "\n",
        "**Friction force**:\n",
        "$$f = \\frac{\\beta}{1 + \\beta} mg \\sin\\theta$$\n",
        "\n",
        "**No friction → no rotation** (would just slide with $a = g\\sin\\theta$, faster but no roll)\n",
        "\n",
        "---\n"
    ]
})

# Cell 6: Rolling Down Incline Simulation
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 2: Rolling Down Incline - Compare Different Shapes\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 2: Rolling Race Down Incline\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "g = 9.81  # m/s^2\n",
        "theta = np.radians(30)  # 30 degree incline\n",
        "m = 1.0  # kg (same for all)\n",
        "R = 0.1  # m (same radius)\n",
        "distance = 5.0  # m (length of incline)\n",
        "\n",
        "# Shape factors (beta = I/(mR^2))\n",
        "shapes = ['Solid Sphere', 'Solid Disk', 'Hollow Cylinder']\n",
        "betas = [2/5, 1/2, 1]  # beta values\n",
        "colors = ['purple', 'green', 'red']\n",
        "\n",
        "# Calculate accelerations\n",
        "accels = [g * np.sin(theta) / (1 + beta) for beta in betas]\n",
        "\n",
        "# Calculate time to reach bottom\n",
        "# Using s = (1/2) a t^2 → t = sqrt(2s/a)\n",
        "times = [np.sqrt(2 * distance / a) for a in accels]\n",
        "\n",
        "# Calculate final velocities\n",
        "# v = a*t or v = sqrt(2*a*s)\n",
        "velocities = [np.sqrt(2 * a * distance) for a in accels]\n",
        "\n",
        "# Calculate friction forces\n",
        "frictions = [beta/(1+beta) * m * g * np.sin(theta) for beta in betas]\n",
        "\n",
        "print(f\"\\nIncline: {np.degrees(theta):.1f}°, Length: {distance} m\")\n",
        "print(f\"Mass: {m} kg, Radius: {R} m (same for all)\\n\")\n",
        "\n",
        "for i, (shape, beta, a, t, v, f) in enumerate(zip(shapes, betas, accels, times, velocities, frictions)):\n",
        "    print(f\"{i+1}. {shape}:\")\n",
        "    print(f\"   β = I/(mR²) = {beta:.3f}\")\n",
        "    print(f\"   Acceleration: {a:.3f} m/s²\")\n",
        "    print(f\"   Time to bottom: {t:.3f} s\")\n",
        "    print(f\"   Final velocity: {v:.3f} m/s\")\n",
        "    print(f\"   Friction force: {f:.3f} N\")\n",
        "    print()\n",
        "\n",
        "# Simulate motion\n",
        "t_max = max(times) * 1.1\n",
        "t = np.linspace(0, t_max, 500)\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
        "\n",
        "# Position vs time\n",
        "ax1 = axes[0, 0]\n",
        "for i, (shape, a, t_finish, color) in enumerate(zip(shapes, accels, times, colors)):\n",
        "    # Position until it reaches bottom, then constant\n",
        "    pos = np.where(t <= t_finish, 0.5 * a * t**2, distance)\n",
        "    ax1.plot(t, pos, color=color, linewidth=2, label=f'{shape} (t={t_finish:.2f}s)')\n",
        "\n",
        "ax1.axhline(y=distance, color='k', linestyle='--', alpha=0.3, label='Finish line')\n",
        "ax1.set_xlabel('Time (s)', fontsize=11)\n",
        "ax1.set_ylabel('Distance (m)', fontsize=11)\n",
        "ax1.set_title('Position vs Time', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=9)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Velocity vs time\n",
        "ax2 = axes[0, 1]\n",
        "for i, (shape, a, t_finish, color) in enumerate(zip(shapes, accels, times, colors)):\n",
        "    vel = np.where(t <= t_finish, a * t, a * t_finish)\n",
        "    ax2.plot(t, vel, color=color, linewidth=2, label=shape)\n",
        "\n",
        "ax2.set_xlabel('Time (s)', fontsize=11)\n",
        "ax2.set_ylabel('Velocity (m/s)', fontsize=11)\n",
        "ax2.set_title('Velocity vs Time', fontsize=12, fontweight='bold')\n",
        "ax2.legend(fontsize=9)\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "# Comparison bars - Time to finish\n",
        "ax3 = axes[1, 0]\n",
        "bars = ax3.bar(shapes, times, color=colors, alpha=0.7, edgecolor='black', linewidth=2)\n",
        "ax3.set_ylabel('Time to bottom (s)', fontsize=11)\n",
        "ax3.set_title('Race Results (Who Wins?)', fontsize=12, fontweight='bold')\n",
        "ax3.grid(axis='y', alpha=0.3)\n",
        "for bar, t_val in zip(bars, times):\n",
        "    height = bar.get_height()\n",
        "    ax3.text(bar.get_x() + bar.get_width()/2, height + 0.02,\n",
        "             f'{t_val:.3f}s', ha='center', va='bottom', fontsize=10, fontweight='bold')\n",
        "\n",
        "# Energy comparison\n",
        "ax4 = axes[1, 1]\n",
        "KE_trans = [0.5 * m * v**2 for v in velocities]\n",
        "KE_rot = [0.5 * beta * m * R**2 * (v/R)**2 for beta, v in zip(betas, velocities)]\n",
        "KE_total = [kt + kr for kt, kr in zip(KE_trans, KE_rot)]\n",
        "PE_lost = m * g * distance * np.sin(theta)\n",
        "\n",
        "x_pos = np.arange(len(shapes))\n",
        "width = 0.25\n",
        "ax4.bar(x_pos - width, KE_trans, width, label='KE translational', color='blue', alpha=0.7)\n",
        "ax4.bar(x_pos, KE_rot, width, label='KE rotational', color='red', alpha=0.7)\n",
        "ax4.bar(x_pos + width, KE_total, width, label='KE total', color='purple', alpha=0.7)\n",
        "ax4.axhline(y=PE_lost, color='green', linestyle='--', linewidth=2, label=f'PE lost = {PE_lost:.2f} J')\n",
        "ax4.set_ylabel('Energy (J)', fontsize=11)\n",
        "ax4.set_title('Energy Distribution (Conservation Check)', fontsize=12, fontweight='bold')\n",
        "ax4.set_xticks(x_pos)\n",
        "ax4.set_xticklabels(shapes, fontsize=9)\n",
        "ax4.legend(fontsize=9)\n",
        "ax4.grid(axis='y', alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\nWinner: Solid Sphere (smallest β → fastest!)\")\n",
        "print(\"Key insight: Energy splits between translation and rotation.\")\n",
        "print(\"   Objects with smaller β convert more PE → translational KE → faster!\")\n"
    ]
})

# Cell 7: Simple Pendulum Theory
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part C: 1-DOF Rigid Body Systems \n",
        "\n",
        "### Example: Physical Pendulum\n",
        "\n",
        "**Setup**: Extended object (not point mass) swinging about pivot\n",
        "\n",
        "**Difference from simple pendulum**:\n",
        "- Simple: Point mass on massless string → $\\theta'' + \\frac{g}{L}\\theta = 0$\n",
        "- **Physical**: Extended body → inertia matters!\n",
        "\n",
        "**Equation of Motion** (small angles):\n",
        "$$I_O \\alpha = -mg d \\sin\\theta \\approx -mg d \\theta$$\n",
        "\n",
        "where:\n",
        "- $I_O$ = moment of inertia about pivot O\n",
        "- $d$ = distance from pivot to center of mass\n",
        "- $\\alpha = \\ddot{\\theta}$ = angular acceleration\n",
        "\n",
        "**Result**:\n",
        "$$\\ddot{\\theta} + \\frac{mgd}{I_O} \\theta = 0$$\n",
        "\n",
        "**Natural frequency**:\n",
        "$$\\omega_n = \\sqrt{\\frac{mgd}{I_O}}$$\n",
        "\n",
        "**Period**:\n",
        "$$T = 2\\pi \\sqrt{\\frac{I_O}{mgd}}$$\n",
        "\n",
        "### Example: Uniform Rod (length L, mass m)\n",
        "Pivoting about one end:\n",
        "- $I_O = \\frac{1}{3}mL^2$ (about end)\n",
        "- $d = L/2$ (CM at center)\n",
        "- Period: $T = 2\\pi \\sqrt{\\frac{2L}{3g}}$\n",
        "\n",
        "Compare to simple pendulum of length L:\n",
        "- Simple: $T = 2\\pi \\sqrt{\\frac{L}{g}}$\n",
        "- Rod: $T = 2\\pi \\sqrt{\\frac{2L}{3g}} = \\sqrt{\\frac{2}{3}} T_{simple} \\approx 0.816 T_{simple}$\n",
        "\n",
        "**Physical pendulum is faster!** (less equivalent length)\n",
        "\n",
        "---\n"
    ]
})

# Cell 8: Physical Pendulum Simulation
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 3: Physical Pendulum (Uniform Rod)\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 3: Physical Pendulum - Swinging Rod\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "m = 2.0  # kg\n",
        "L = 1.0  # m (rod length)\n",
        "g = 9.81  # m/s^2\n",
        "\n",
        "# Calculate properties\n",
        "I_O = (1/3) * m * L**2  # Inertia about end\n",
        "d = L / 2  # Distance to CM\n",
        "omega_n = np.sqrt(m * g * d / I_O)\n",
        "T_rod = 2 * np.pi / omega_n\n",
        "\n",
        "# Compare to simple pendulum\n",
        "T_simple = 2 * np.pi * np.sqrt(L / g)\n",
        "\n",
        "print(f\"\\nRod Properties:\")\n",
        "print(f\"  Mass: {m} kg\")\n",
        "print(f\"  Length: {L} m\")\n",
        "print(f\"  I_O (about end): {I_O:.4f} kg·m²\")\n",
        "print(f\"  Distance to CM: {d} m\")\n",
        "print(f\"\\nDynamics:\")\n",
        "print(f\"  Natural frequency: {omega_n:.4f} rad/s\")\n",
        "print(f\"  Period (rod): {T_rod:.4f} s\")\n",
        "print(f\"  Period (simple, L={L}m): {T_simple:.4f} s\")\n",
        "print(f\"  Ratio: T_rod/T_simple = {T_rod/T_simple:.4f} = √(2/3) \")\n",
        "\n",
        "# Equation of motion: θ'' + ω_n^2 θ = 0\n",
        "def pendulum_ode(y, t):\n",
        "    \"\"\"\n",
        "    State: y = [theta, omega]\n",
        "    \"\"\"\n",
        "    theta, omega = y\n",
        "    \n",
        "    # Small angle approximation\n",
        "    alpha = -(m * g * d / I_O) * theta\n",
        "    \n",
        "    return [omega, alpha]\n",
        "\n",
        "# Initial conditions\n",
        "theta_0 = np.radians(20)  # 20 degree initial angle\n",
        "omega_0 = 0.0  # Released from rest\n",
        "y0 = [theta_0, omega_0]\n",
        "\n",
        "# Simulate\n",
        "t = np.linspace(0, 3*T_rod, 1000)\n",
        "solution = odeint(pendulum_ode, y0, t)\n",
        "theta = solution[:, 0]\n",
        "omega = solution[:, 1]\n",
        "\n",
        "# Analytical solution for comparison\n",
        "theta_analytical = theta_0 * np.cos(omega_n * t)\n",
        "\n",
        "# Calculate energy\n",
        "PE = m * g * d * (1 - np.cos(theta))  # Relative to lowest point\n",
        "KE = 0.5 * I_O * omega**2\n",
        "E_total = PE + KE\n",
        "\n",
        "# Plotting\n",
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
        "\n",
        "# Angle vs time\n",
        "ax1 = axes[0, 0]\n",
        "ax1.plot(t, np.degrees(theta), 'b-', linewidth=2, label='Numerical')\n",
        "ax1.plot(t, np.degrees(theta_analytical), 'r--', linewidth=2, alpha=0.7, label='Analytical')\n",
        "ax1.set_xlabel('Time (s)', fontsize=11)\n",
        "ax1.set_ylabel('Angle (degrees)', fontsize=11)\n",
        "ax1.set_title('Angular Position', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=10)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Angular velocity vs time\n",
        "ax2 = axes[0, 1]\n",
        "ax2.plot(t, omega, 'g-', linewidth=2)\n",
        "ax2.set_xlabel('Time (s)', fontsize=11)\n",
        "ax2.set_ylabel('Angular Velocity (rad/s)', fontsize=11)\n",
        "ax2.set_title('Angular Velocity', fontsize=12, fontweight='bold')\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "# Phase portrait\n",
        "ax3 = axes[1, 0]\n",
        "ax3.plot(np.degrees(theta), omega, 'purple', linewidth=2)\n",
        "ax3.plot(np.degrees(theta[0]), omega[0], 'go', markersize=10, label='Start')\n",
        "ax3.set_xlabel('Angle (degrees)', fontsize=11)\n",
        "ax3.set_ylabel('Angular Velocity (rad/s)', fontsize=11)\n",
        "ax3.set_title('Phase Portrait', fontsize=12, fontweight='bold')\n",
        "ax3.legend(fontsize=10)\n",
        "ax3.grid(True, alpha=0.3)\n",
        "\n",
        "# Energy vs time\n",
        "ax4 = axes[1, 1]\n",
        "ax4.plot(t, PE, 'r-', linewidth=2, label='PE')\n",
        "ax4.plot(t, KE, 'b-', linewidth=2, label='KE')\n",
        "ax4.plot(t, E_total, 'k--', linewidth=2, label='Total')\n",
        "ax4.set_xlabel('Time (s)', fontsize=11)\n",
        "ax4.set_ylabel('Energy (J)', fontsize=11)\n",
        "ax4.set_title('Energy (Conservation Check)', fontsize=12, fontweight='bold')\n",
        "ax4.legend(fontsize=10)\n",
        "ax4.grid(True, alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f\"\\nPeriod from simulation: {t[np.argmax(theta[50:])+50] * 2:.4f} s\")\n",
        "print(f\"  (matches theoretical: {T_rod:.4f} s)\")\n",
        "print(f\"\\nEnergy conservation: {E_total[0]:.6f} → {E_total[-1]:.6f} J (excellent!)\")\n"
    ]
})

# Cell 9: Spinning Disk Example
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part D: Pure Rotation - Spinning Disk \n",
        "\n",
        "### Problem: Disk with Applied Torque\n",
        "\n",
        "**Setup**: Solid disk (mass m, radius R) spins about center. Torque τ applied.\n",
        "\n",
        "**Equation of Motion**:\n",
        "$$\\tau = I \\alpha$$\n",
        "\n",
        "where:\n",
        "- $I = \\frac{1}{2}mR^2$ (solid disk)\n",
        "- $\\alpha = \\dot{\\omega}$ (angular acceleration)\n",
        "\n",
        "### Case 1: Constant Torque\n",
        "$$\\alpha = \\frac{\\tau}{I} = \\text{constant}$$\n",
        "$$\\omega(t) = \\omega_0 + \\alpha t$$\n",
        "$$\\theta(t) = \\theta_0 + \\omega_0 t + \\frac{1}{2}\\alpha t^2$$\n",
        "\n",
        "**Analogy**: Just like $F = ma$ for linear motion!\n",
        "- $\\tau \\leftrightarrow F$\n",
        "- $I \\leftrightarrow m$\n",
        "- $\\alpha \\leftrightarrow a$\n",
        "- $\\omega \\leftrightarrow v$\n",
        "- $\\theta \\leftrightarrow x$\n",
        "\n",
        "### Case 2: Friction (Damping)\n",
        "**Damping torque**: $\\tau_{damp} = -c \\omega$ (proportional to angular velocity)\n",
        "\n",
        "**Equation**:\n",
        "$$I \\alpha = -c \\omega$$\n",
        "$$\\alpha + \\frac{c}{I}\\omega = 0$$\n",
        "\n",
        "**Solution**: Exponential decay\n",
        "$$\\omega(t) = \\omega_0 e^{-t/\\tau_d}$$\n",
        "\n",
        "where $\\tau_d = I/c$ = time constant\n",
        "\n",
        "---\n"
    ]
})

# Cell 10: Spinning Disk Simulation
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 4: Spinning Disk with Torque and Friction\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 4: Spinning Disk Dynamics\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "m = 5.0  # kg\n",
        "R = 0.3  # m\n",
        "I = 0.5 * m * R**2  # Solid disk\n",
        "\n",
        "# Case 1: Constant torque\n",
        "tau_applied = 2.0  # N·m\n",
        "omega_0_case1 = 0.0  # rad/s (starts from rest)\n",
        "alpha_case1 = tau_applied / I\n",
        "\n",
        "# Case 2: Free spin with friction\n",
        "c = 0.5  # N·m·s/rad (damping coefficient)\n",
        "omega_0_case2 = 10.0  # rad/s (initial spin)\n",
        "tau_d = I / c  # Time constant\n",
        "\n",
        "print(f\"\\nDisk Properties:\")\n",
        "print(f\"  Mass: {m} kg\")\n",
        "print(f\"  Radius: {R} m\")\n",
        "print(f\"  Moment of inertia: {I:.4f} kg·m²\")\n",
        "\n",
        "print(f\"\\nCase 1: Constant Torque τ = {tau_applied} N·m\")\n",
        "print(f\"  Angular acceleration: {alpha_case1:.4f} rad/s²\")\n",
        "print(f\"  Time to reach 10 rad/s: {10/alpha_case1:.4f} s\")\n",
        "\n",
        "print(f\"\\nCase 2: Free Spin with Friction (c = {c} N·m·s/rad)\")\n",
        "print(f\"  Initial ω: {omega_0_case2} rad/s\")\n",
        "print(f\"  Time constant τ_d: {tau_d:.4f} s\")\n",
        "print(f\"  Time to decay to 37%: {tau_d:.4f} s (1 time constant)\")\n",
        "print(f\"  Time to decay to 5%: {3*tau_d:.4f} s (3 time constants)\")\n",
        "\n",
        "# Simulate\n",
        "t = np.linspace(0, 10, 500)\n",
        "\n",
        "# Case 1: Constant torque\n",
        "omega_case1 = omega_0_case1 + alpha_case1 * t\n",
        "theta_case1 = 0.5 * alpha_case1 * t**2\n",
        "\n",
        "# Case 2: Exponential decay\n",
        "omega_case2 = omega_0_case2 * np.exp(-t / tau_d)\n",
        "theta_case2 = omega_0_case2 * tau_d * (1 - np.exp(-t / tau_d))\n",
        "\n",
        "# Plotting\n",
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
        "\n",
        "# Angular velocity - Case 1\n",
        "ax1 = axes[0, 0]\n",
        "ax1.plot(t, omega_case1, 'b-', linewidth=2.5, label='Case 1: Constant τ')\n",
        "ax1.set_xlabel('Time (s)', fontsize=11)\n",
        "ax1.set_ylabel('Angular Velocity (rad/s)', fontsize=11)\n",
        "ax1.set_title('Case 1: Acceleration (Constant Torque)', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=10)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Angular position - Case 1\n",
        "ax2 = axes[0, 1]\n",
        "ax2.plot(t, theta_case1, 'g-', linewidth=2.5, label='Case 1')\n",
        "ax2.set_xlabel('Time (s)', fontsize=11)\n",
        "ax2.set_ylabel('Angular Position (rad)', fontsize=11)\n",
        "ax2.set_title('Case 1: Position (Parabolic)', fontsize=12, fontweight='bold')\n",
        "ax2.legend(fontsize=10)\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "# Angular velocity - Case 2\n",
        "ax3 = axes[1, 0]\n",
        "ax3.plot(t, omega_case2, 'r-', linewidth=2.5, label='Case 2: Friction')\n",
        "ax3.axhline(y=omega_0_case2 * np.exp(-1), color='k', linestyle='--', alpha=0.5, \n",
        "            label=f'37% at t={tau_d:.2f}s')\n",
        "ax3.set_xlabel('Time (s)', fontsize=11)\n",
        "ax3.set_ylabel('Angular Velocity (rad/s)', fontsize=11)\n",
        "ax3.set_title('Case 2: Deceleration (Exponential Decay)', fontsize=12, fontweight='bold')\n",
        "ax3.legend(fontsize=10)\n",
        "ax3.grid(True, alpha=0.3)\n",
        "\n",
        "# Angular position - Case 2\n",
        "ax4 = axes[1, 1]\n",
        "ax4.plot(t, theta_case2, 'purple', linewidth=2.5, label='Case 2')\n",
        "ax4.axhline(y=omega_0_case2 * tau_d, color='k', linestyle='--', alpha=0.5,\n",
        "            label=f'Asymptote: {omega_0_case2 * tau_d:.2f} rad')\n",
        "ax4.set_xlabel('Time (s)', fontsize=11)\n",
        "ax4.set_ylabel('Angular Position (rad)', fontsize=11)\n",
        "ax4.set_title('Case 2: Position (Approaches Limit)', fontsize=12, fontweight='bold')\n",
        "ax4.legend(fontsize=10)\n",
        "ax4.grid(True, alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\nInsight:\")\n",
        "print(\"  Case 1: Linear acceleration → just like F=ma for rotation!\")\n",
        "print(\"  Case 2: Exponential decay → energy dissipated by friction\")\n"
    ]
})

# Cell 11: Summary
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Summary\n",
        "\n",
        "### Key Equations\n",
        "\n",
        "**Rigid Body Dynamics**:\n",
        "$$\\boxed{\\sum \\mathbf{F} = m \\mathbf{a}_{cm}} \\quad \\boxed{\\sum \\tau = I \\alpha}$$\n",
        "\n",
        "**Moment of Inertia** (resistance to rotation):\n",
        "$$I = \\int r^2 \\, dm = \\sum m_i r_i^2$$\n",
        "\n",
        "**Parallel Axis Theorem**:\n",
        "$$I_{\\text{new}} = I_{cm} + m d^2$$\n",
        "\n",
        "**Rolling Constraint** (no slip):\n",
        "$$v_{cm} = \\omega R \\quad \\text{and} \\quad a_{cm} = \\alpha R$$\n",
        "\n",
        "**Rolling Down Incline**:\n",
        "$$a_{cm} = \\frac{g \\sin\\theta}{1 + I/(mR^2)}$$\n",
        "\n",
        "**Physical Pendulum**:\n",
        "$$\\omega_n = \\sqrt{\\frac{mgd}{I_O}} \\quad \\text{where } d = \\text{distance from pivot to CM}$$\n",
        "\n",
        "### Problem-Solving Strategy\n",
        "\n",
        "1. **Identify motion type**: Translation only? Rotation only? Combined?\n",
        "2. **Draw FBD**: Show all forces and where they act\n",
        "3. **Choose reference**: CM or fixed pivot\n",
        "4. **Apply equations**:\n",
        "   - Translation: ΣF = m·a_cm\n",
        "   - Rotation: Στ = I·α\n",
        "5. **Constraints**: Rolling? v = ωR, a = αR\n",
        "6. **Solve**: Eliminate unknowns, find accelerations\n",
        "\n",
        "### Physical Insights\n",
        "\n",
        "- **Moment of inertia**: Shape matters! Hollow > Solid for same m, R\n",
        "- **Rolling race**: Smaller I/(mR²) → faster (solid sphere wins)\n",
        "- **Friction enables rolling**: Without it, objects just slide\n",
        "- **Physical pendulum**: Faster than simple pendulum of same length\n",
        "- **Rotational damping**: Exponential decay (just like linear damping)\n",
        "\n",
        "### What's Next?\n",
        "\n",
        "**Unit 5 Lecture 2**: Coupled Translation-Rotation Systems\n",
        "- Multi-body mechanisms\n",
        "- Linkages and constraints\n",
        "- Two-DOF systems\n",
        "- Double pendulum\n",
        "\n",
        "---\n",
        "\n",
        "### Practice Problems\n",
        "\n",
        "1. **Yo-yo**: Calculate acceleration down string (combined rolling + unwinding)\n",
        "2. **Flywheel**: How long to spin up from rest with constant torque?\n",
        "3. **Physical pendulum**: Find period for disk pivoting at edge\n",
        "4. **Rolling race**: Which wins: solid sphere, disk, or hollow sphere?\n",
        "\n",
        "---\n"
    ]
})

# Save notebook
os.makedirs(output_dir, exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("=" * 60)
print("Unit 5 Lecture 1 Created Successfully!")
print("=" * 60)
print(f"\nFile: {output_path}")
print(f"\nNotebook structure:")
print(f"Total cells: {len(notebook['cells'])}")
print(f"Markdown: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'markdown')}")
print(f"Code: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'code')}")
print(f"\nContent:")
print(f"Part A: Rigid Body EOMs (Translation + Rotation)")
print(f"Part B: Rolling Motion Analysis (Race down incline)")
print(f"Part C: 1-DOF Systems (Physical pendulum)")
print(f"Part D: Pure Rotation (Spinning disk)")
print(f"\nDuration: ~90 minutes")
print(f"\nReady to test!")