import json
import os

# Output configuration
output_dir = "notebooks/Teacher"
output_path = os.path.join(output_dir, "T_U5_P1_Modal_Testing_Practical.ipynb")

# Initialize notebook structure
notebook = {
    "cells": [],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.14.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

# Cell 1: Header
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# Unit 5 Practical 1: Modal Testing & System Identification\n",
        "## Experimental Modal Analysis Simulation\n",
        "\n",
        "### Objectives\n",
        "1. Simulate experimental modal analysis (EMA) procedure\n",
        "2. Extract natural frequencies from measurements\n",
        "3. Calculate damping ratios from decay\n",
        "4. Identify mode shapes from multi-point measurements\n",
        "5. Validate results against theoretical model\n",
        "\n",
        "### Scenario\n",
        "You have an unknown 3-DOF structure and need to characterize it:\n",
        "- Perform hammer test (impact excitation)\n",
        "- Measure accelerations at multiple points\n",
        "- Process data to extract modal parameters\n",
        "- Compare with finite element predictions\n",
        "\n",
        "### Tools & Methods\n",
        "- **Hammer test**: Broadband excitation\n",
        "- **FFT analysis**: Frequency domain processing\n",
        "- **Peak picking**: Extract natural frequencies\n",
        "- **Half-power method**: Calculate damping\n",
        "- **Mode shape extraction**: From FRF phase\n",
        "- **MAC**: Modal assurance criterion for validation\n",
        "\n",
        "---\n"
    ]
})

# Cell 2: Imports
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from scipy.integrate import odeint\n",
        "from scipy.signal import find_peaks, hilbert\n",
        "from scipy.fft import fft, fftfreq\n",
        "\n",
        "# Plot styling\n",
        "plt.rcParams['figure.figsize'] = (14, 10)\n",
        "plt.rcParams['font.size'] = 10\n",
        "\n",
        "print(\"Libraries imported successfully!\")\n",
        "print(\"Ready for modal testing...\")\n"
    ]
})

# Cell 3: Part 1 - Define Unknown System
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part 1: The \"Unknown\" Structure\n",
        "\n",
        "### System Description\n",
        "3-DOF structure: 3 masses connected by springs and dampers\n",
        "```\n",
        "Wall--[k1,c1]--[m1]--[k2,c2]--[m2]--[k3,c3]--[m3]--[k4,c4]--Wall\n",
        "```\n",
        "\n",
        "### Your Task\n",
        "Pretend you don't know the parameters. Extract them from measurements!\n",
        "\n",
        "### Hidden Parameters\n",
        "(In reality, we'll use these to generate synthetic data)\n",
        "- Masses: m1=2kg, m2=1.5kg, m3=1kg\n",
        "- Stiffnesses: k1=k4=100 N/m, k2=k3=150 N/m\n",
        "- Damping: 3% modal damping in each mode\n",
        "\n",
        "---\n"
    ]
})

# Cell 4: Generate Synthetic Data
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Part 1: Define the hidden system\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Part 1: Generate Synthetic Measurement Data\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Hidden system parameters\n",
        "m1, m2, m3 = 2.0, 1.5, 1.0  # kg\n",
        "k1, k2, k3, k4 = 100.0, 150.0, 150.0, 100.0  # N/m\n",
        "\n",
        "# Mass and stiffness matrices\n",
        "M = np.diag([m1, m2, m3])\n",
        "K = np.array([\n",
        "    [k1+k2, -k2, 0],\n",
        "    [-k2, k2+k3, -k3],\n",
        "    [0, -k3, k3+k4]\n",
        "])\n",
        "\n",
        "print(\"\\nHidden System (we pretend we don't know this):\")\n",
        "print(f\"  Masses: [{m1}, {m2}, {m3}] kg\")\n",
        "print(f\"  Stiffnesses: [{k1}, {k2}, {k3}, {k4}] N/m\")\n",
        "\n",
        "# Solve for theoretical modes\n",
        "M_inv = np.linalg.inv(M)\n",
        "A = M_inv @ K\n",
        "eigenvalues, eigenvectors = np.linalg.eig(A)\n",
        "\n",
        "# Sort\n",
        "idx = np.argsort(eigenvalues)\n",
        "eigenvalues = eigenvalues[idx]\n",
        "eigenvectors = eigenvectors[:, idx]\n",
        "\n",
        "omega_n_true = np.sqrt(eigenvalues)\n",
        "f_n_true = omega_n_true / (2 * np.pi)\n",
        "\n",
        "# Mass-normalize mode shapes\n",
        "mode_shapes_true = np.zeros_like(eigenvectors)\n",
        "for i in range(3):\n",
        "    phi = eigenvectors[:, i]\n",
        "    modal_mass = phi.T @ M @ phi\n",
        "    mode_shapes_true[:, i] = phi / np.sqrt(modal_mass)\n",
        "\n",
        "print(\"\\nTrue Natural Frequencies:\")\n",
        "for i in range(3):\n",
        "    print(f\"  Mode {i+1}: {f_n_true[i]:.3f} Hz\")\n",
        "\n",
        "print(\"\\nTrue Mode Shapes (normalized):\")\n",
        "for i in range(3):\n",
        "    print(f\"  Mode {i+1}: [{mode_shapes_true[0,i]:.4f}, {mode_shapes_true[1,i]:.4f}, {mode_shapes_true[2,i]:.4f}]\")\n",
        "\n",
        "# Add proportional damping (3% in each mode)\n",
        "zeta_modal = np.array([0.03, 0.03, 0.03])\n",
        "\n",
        "print(\"\\nDamping: 3% in each mode\")\n",
        "print(\"\\nNow let's pretend we don't know these values...\")\n",
        "print(\"Time to do experimental modal analysis!\")\n"
    ]
})

# Cell 5: Hammer Test Simulation
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part 2: Hammer Test - Impact Excitation\n",
        "\n",
        "### Procedure\n",
        "1. Strike mass 1 with hammer (impulse)\n",
        "2. Measure acceleration at all 3 masses\n",
        "3. Record free decay response\n",
        "4. Add realistic measurement noise\n",
        "\n",
        "### Why Hammer Test?\n",
        "- **Broadband**: Impulse contains all frequencies\n",
        "- **Quick**: One hit gives full response\n",
        "- **Portable**: No need for shaker or fixtures\n",
        "- **Standard**: Used in aerospace, automotive, civil\n",
        "\n",
        "### Impulse Modeling\n",
        "- Short duration pulse (1-5 ms typical)\n",
        "- Integrated force = momentum change\n",
        "- Approximated as initial velocity\n",
        "\n",
        "---\n"
    ]
})

# Cell 6: Simulate Hammer Test
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Part 2: Simulate hammer test\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Part 2: Hammer Test Simulation\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "def modal_ode_damped(q, t, omega_n, zeta):\n",
        "    \"\"\"3-DOF modal equations with damping\"\"\"\n",
        "    n = 3\n",
        "    q_pos = q[:n]\n",
        "    q_vel = q[n:]\n",
        "    \n",
        "    q_acc = np.zeros(n)\n",
        "    for i in range(n):\n",
        "        q_acc[i] = -2*zeta[i]*omega_n[i]*q_vel[i] - omega_n[i]**2*q_pos[i]\n",
        "    \n",
        "    return np.concatenate([q_vel, q_acc])\n",
        "\n",
        "# Simulate hammer impact on mass 1\n",
        "# Impulse J = F*dt creates initial velocity v0 = J/m1\n",
        "impulse = 1.0  # N*s\n",
        "v0_phys = np.array([impulse/m1, 0, 0])  # Only m1 gets velocity\n",
        "x0_phys = np.array([0, 0, 0])  # Start from equilibrium\n",
        "\n",
        "print(\"\\nHammer Test Setup:\")\n",
        "print(f\"  Impact on: Mass 1\")\n",
        "print(f\"  Impulse: {impulse} N*s\")\n",
        "print(f\"  Initial velocity: v1 = {v0_phys[0]:.3f} m/s\")\n",
        "\n",
        "# Transform to modal coordinates\n",
        "q0 = mode_shapes_true.T @ M @ x0_phys\n",
        "q_dot0 = mode_shapes_true.T @ M @ v0_phys\n",
        "\n",
        "# Time array (sample at 1000 Hz for 5 seconds)\n",
        "fs = 1000  # Hz\n",
        "duration = 5  # seconds\n",
        "t = np.linspace(0, duration, fs * duration)\n",
        "dt = t[1] - t[0]\n",
        "\n",
        "# Solve modal equations\n",
        "y0 = np.concatenate([q0, q_dot0])\n",
        "solution = odeint(modal_ode_damped, y0, t, args=(omega_n_true, zeta_modal))\n",
        "\n",
        "# Extract modal coordinates\n",
        "q_modal = solution[:, :3]\n",
        "q_dot_modal = solution[:, 3:]\n",
        "\n",
        "# Transform to physical coordinates\n",
        "x_phys = (mode_shapes_true @ q_modal.T).T\n",
        "v_phys = (mode_shapes_true @ q_dot_modal.T).T\n",
        "a_phys = np.zeros_like(v_phys)\n",
        "\n",
        "# Calculate accelerations\n",
        "for i in range(len(t)):\n",
        "    q_acc = np.zeros(3)\n",
        "    for j in range(3):\n",
        "        q_acc[j] = -2*zeta_modal[j]*omega_n_true[j]*q_dot_modal[i,j] - omega_n_true[j]**2*q_modal[i,j]\n",
        "    a_phys[i, :] = mode_shapes_true @ q_acc\n",
        "\n",
        "# Add realistic measurement noise\n",
        "np.random.seed(42)\n",
        "noise_level = 0.02  # m/s^2 RMS\n",
        "a_measured = a_phys + noise_level * np.random.randn(*a_phys.shape)\n",
        "\n",
        "print(f\"\\nMeasurement:\")\n",
        "print(f\"  Sampling rate: {fs} Hz\")\n",
        "print(f\"  Duration: {duration} s\")\n",
        "print(f\"  Samples: {len(t)}\")\n",
        "print(f\"  Noise level: {noise_level*1000:.1f} mm/s^2 RMS\")\n",
        "\n",
        "# Plot time series\n",
        "fig, axes = plt.subplots(3, 1, figsize=(14, 10))\n",
        "\n",
        "for i in range(3):\n",
        "    ax = axes[i]\n",
        "    ax.plot(t[:2000], a_measured[:2000, i], 'b-', linewidth=0.8, alpha=0.7)\n",
        "    ax.set_xlabel('Time (s)', fontsize=11)\n",
        "    ax.set_ylabel(f'Acceleration m{i+1} (m/s^2)', fontsize=11)\n",
        "    ax.set_title(f'Measured Response: Mass {i+1}', fontsize=12, fontweight='bold')\n",
        "    ax.grid(True, alpha=0.3)\n",
        "    ax.set_xlim([0, 2])\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\nData collected! Ready for analysis...\")\n"
    ]
})

# Cell 7: FFT and Peak Picking
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part 3: Frequency Domain Analysis\n",
        "\n",
        "### FFT Processing\n",
        "1. Apply FFT to acceleration data\n",
        "2. Identify peaks in magnitude spectrum\n",
        "3. Each peak corresponds to natural frequency\n",
        "\n",
        "### Peak Picking Algorithm\n",
        "- Find local maxima in FFT magnitude\n",
        "- Filter by prominence (reject noise)\n",
        "- Extract frequency at each peak\n",
        "\n",
        "### Half-Power Method for Damping\n",
        "At resonance peak:\n",
        "- $f_r$ = resonance frequency\n",
        "- $f_1, f_2$ = frequencies where amplitude = peak/sqrt(2)\n",
        "- $\\\\zeta \\\\approx \\\\frac{f_2 - f_1}{2f_r}$ (bandwidth method)\n",
        "\n",
        "---\n"
    ]
})

# Cell 8: Extract Natural Frequencies
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Part 3: FFT and Peak Picking\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Part 3: Frequency Domain Analysis\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# FFT of acceleration signal (mass 1)\n",
        "N = len(t)\n",
        "freq = fftfreq(N, dt)[:N//2]\n",
        "A1_fft = fft(a_measured[:, 0])[:N//2]\n",
        "A1_mag = np.abs(A1_fft) / N\n",
        "\n",
        "# Find peaks\n",
        "peaks, properties = find_peaks(A1_mag, prominence=0.001, distance=50)\n",
        "peak_freqs = freq[peaks]\n",
        "peak_mags = A1_mag[peaks]\n",
        "\n",
        "# Sort by magnitude\n",
        "idx_sorted = np.argsort(peak_mags)[::-1]\n",
        "peak_freqs = peak_freqs[idx_sorted][:3]  # Take 3 largest\n",
        "peak_mags = peak_mags[idx_sorted][:3]\n",
        "peak_freqs = np.sort(peak_freqs)  # Sort by frequency\n",
        "\n",
        "f_n_measured = peak_freqs\n",
        "\n",
        "print(\"\\nExtracted Natural Frequencies (from FFT peaks):\")\n",
        "for i in range(3):\n",
        "    error = abs(f_n_measured[i] - f_n_true[i]) / f_n_true[i] * 100\n",
        "    print(f\"  Mode {i+1}: {f_n_measured[i]:.3f} Hz (true: {f_n_true[i]:.3f} Hz, error: {error:.2f}%)\")\n",
        "\n",
        "# Plot FFT with peaks\n",
        "fig, ax = plt.subplots(1, 1, figsize=(14, 6))\n",
        "\n",
        "ax.plot(freq, A1_mag, 'b-', linewidth=1, alpha=0.7, label='FFT Magnitude')\n",
        "ax.plot(f_n_measured, A1_mag[peaks[idx_sorted][:3]], 'ro', markersize=10, label='Identified Peaks')\n",
        "\n",
        "# Mark true frequencies\n",
        "for i, f in enumerate(f_n_true):\n",
        "    ax.axvline(x=f, color='g', linestyle='--', alpha=0.5, linewidth=2)\n",
        "\n",
        "ax.set_xlabel('Frequency (Hz)', fontsize=11)\n",
        "ax.set_ylabel('Magnitude (m/s^2)', fontsize=11)\n",
        "ax.set_title('FFT Spectrum: Peak Picking for Natural Frequencies', fontsize=12, fontweight='bold')\n",
        "ax.legend(fontsize=10)\n",
        "ax.grid(True, alpha=0.3)\n",
        "ax.set_xlim([0, 5])\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\nFrequency identification complete!\")\n"
    ]
})

# Cell 9: Damping Extraction
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Part 4: Damping Extraction - Logarithmic Decrement\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Part 4: Damping Ratio Extraction\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Method: Logarithmic decrement from time decay\n",
        "# Use displacement signal (integrate acceleration twice)\n",
        "from scipy.integrate import cumtrapz\n",
        "\n",
        "v1 = cumtrapz(a_measured[:, 0], t, initial=0)\n",
        "x1 = cumtrapz(v1, t, initial=0)\n",
        "\n",
        "# Find peaks in displacement\n",
        "peaks_x, _ = find_peaks(x1[:2000], distance=50)  # First 2 seconds\n",
        "\n",
        "if len(peaks_x) >= 5:\n",
        "    # Calculate log decrements\n",
        "    peak_amps = x1[peaks_x[:10]]  # Use first 10 peaks\n",
        "    deltas = []\n",
        "    for i in range(len(peak_amps)-1):\n",
        "        if peak_amps[i+1] > 0 and peak_amps[i] > 0:\n",
        "            delta = np.log(peak_amps[i] / peak_amps[i+1])\n",
        "            deltas.append(delta)\n",
        "    \n",
        "    delta_avg = np.mean(deltas)\n",
        "    zeta_measured = delta_avg / np.sqrt(4*np.pi**2 + delta_avg**2)\n",
        "    \n",
        "    print(\"\\nDamping Extraction (Logarithmic Decrement):\")\n",
        "    print(f\"  Peaks found: {len(peaks_x)}\")\n",
        "    print(f\"  Average log decrement: delta = {delta_avg:.4f}\")\n",
        "    print(f\"  Extracted damping ratio: zeta = {zeta_measured:.4f}\")\n",
        "    print(f\"  True damping ratio: zeta = {zeta_modal[0]:.4f}\")\n",
        "    print(f\"  Error: {abs(zeta_measured - zeta_modal[0])/zeta_modal[0]*100:.1f}%\")\n",
        "else:\n",
        "    zeta_measured = 0.03\n",
        "    print(\"\\nInsufficient peaks for log decrement, using nominal value\")\n",
        "\n",
        "# Alternative: Half-power bandwidth method from FFT\n",
        "print(\"\\nHalf-Power Bandwidth Method (from FFT):\")\n",
        "zeta_hp = []\n",
        "for i, f_res in enumerate(f_n_measured):\n",
        "    # Find peak index\n",
        "    idx_peak = np.argmin(np.abs(freq - f_res))\n",
        "    peak_mag = A1_mag[idx_peak]\n",
        "    \n",
        "    # Find half-power points\n",
        "    half_power = peak_mag / np.sqrt(2)\n",
        "    idx_left = np.where((freq < f_res) & (A1_mag > half_power))[0]\n",
        "    idx_right = np.where((freq > f_res) & (A1_mag > half_power))[0]\n",
        "    \n",
        "    if len(idx_left) > 0 and len(idx_right) > 0:\n",
        "        f1 = freq[idx_left[-1]]\n",
        "        f2 = freq[idx_right[0]]\n",
        "        zeta_i = (f2 - f1) / (2 * f_res)\n",
        "        zeta_hp.append(zeta_i)\n",
        "        print(f\"  Mode {i+1}: zeta = {zeta_i:.4f} (bandwidth: {f2-f1:.4f} Hz)\")\n",
        "    else:\n",
        "        zeta_hp.append(0.03)\n",
        "        print(f\"  Mode {i+1}: Cannot resolve bandwidth (using nominal)\")\n",
        "\n",
        "print(\"\\nDamping identification complete!\")\n"
    ]
})

# Cell 10: Mode Shape Extraction
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part 5: Mode Shape Identification\n",
        "\n",
        "### Procedure\n",
        "1. Extract FFT amplitude at each natural frequency\n",
        "2. For each mode, amplitude ratio = mode shape ratio\n",
        "3. Normalize mode shapes\n",
        "4. Compare with theoretical prediction\n",
        "\n",
        "### Modal Assurance Criterion (MAC)\n",
        "Correlation between measured and theoretical mode shapes:\n",
        "$$\\\\text{MAC}(\\\\phi_i, \\\\psi_i) = \\\\frac{|\\\\phi_i^T \\\\psi_i|^2}{(\\\\phi_i^T \\\\phi_i)(\\\\psi_i^T \\\\psi_i)}$$\n",
        "\n",
        "- MAC = 1: Perfect match\n",
        "- MAC > 0.9: Good correlation\n",
        "- MAC < 0.8: Poor correlation\n",
        "\n",
        "---\n"
    ]
})

# Cell 11: Extract Mode Shapes
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Part 5: Mode Shape Extraction\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Part 5: Mode Shape Identification\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# FFT for all three masses\n",
        "A_fft_all = np.zeros((3, N//2), dtype=complex)\n",
        "for i in range(3):\n",
        "    A_fft_all[i, :] = fft(a_measured[:, i])[:N//2]\n",
        "\n",
        "# Extract mode shapes from FFT amplitude at resonance\n",
        "mode_shapes_measured = np.zeros((3, 3))\n",
        "\n",
        "for i, f_res in enumerate(f_n_measured):\n",
        "    # Find frequency bin\n",
        "    idx_freq = np.argmin(np.abs(freq - f_res))\n",
        "    \n",
        "    # Extract amplitudes at this frequency\n",
        "    mode_amps = np.abs(A_fft_all[:, idx_freq])\n",
        "    \n",
        "    # Normalize (max amplitude = 1)\n",
        "    mode_amps = mode_amps / np.max(mode_amps)\n",
        "    \n",
        "    mode_shapes_measured[:, i] = mode_amps\n",
        "\n",
        "print(\"\\nExtracted Mode Shapes (from FRF amplitudes):\")\n",
        "for i in range(3):\n",
        "    print(f\"  Mode {i+1}: [{mode_shapes_measured[0,i]:.4f}, {mode_shapes_measured[1,i]:.4f}, {mode_shapes_measured[2,i]:.4f}]\")\n",
        "\n",
        "# Normalize theoretical mode shapes for comparison\n",
        "mode_shapes_theory_norm = np.zeros_like(mode_shapes_true)\n",
        "for i in range(3):\n",
        "    mode_shapes_theory_norm[:, i] = mode_shapes_true[:, i] / np.max(np.abs(mode_shapes_true[:, i]))\n",
        "\n",
        "print(\"\\nTheoretical Mode Shapes (normalized):\")\n",
        "for i in range(3):\n",
        "    print(f\"  Mode {i+1}: [{mode_shapes_theory_norm[0,i]:.4f}, {mode_shapes_theory_norm[1,i]:.4f}, {mode_shapes_theory_norm[2,i]:.4f}]\")\n",
        "\n",
        "# Calculate MAC (Modal Assurance Criterion)\n",
        "MAC = np.zeros((3, 3))\n",
        "for i in range(3):\n",
        "    for j in range(3):\n",
        "        phi_i = mode_shapes_measured[:, i]\n",
        "        psi_j = mode_shapes_theory_norm[:, j]\n",
        "        numerator = abs(np.dot(phi_i, psi_j))**2\n",
        "        denominator = np.dot(phi_i, phi_i) * np.dot(psi_j, psi_j)\n",
        "        MAC[i, j] = numerator / denominator\n",
        "\n",
        "print(\"\\nModal Assurance Criterion (MAC):\")\n",
        "print(\"  (Measured vs. Theoretical)\")\n",
        "print(\"         Mode 1  Mode 2  Mode 3\")\n",
        "for i in range(3):\n",
        "    print(f\"  Mode {i+1}:  {MAC[i,0]:.4f}  {MAC[i,1]:.4f}  {MAC[i,2]:.4f}\")\n",
        "\n",
        "# Plot mode shapes\n",
        "fig, axes = plt.subplots(1, 3, figsize=(16, 5))\n",
        "\n",
        "x_pos = np.array([0, 1, 2, 3])  # Positions: wall, m1, m2, m3\n",
        "\n",
        "for i in range(3):\n",
        "    ax = axes[i]\n",
        "    \n",
        "    # Measured\n",
        "    mode_viz_meas = np.concatenate([[0], mode_shapes_measured[:, i]])\n",
        "    ax.plot(x_pos, mode_viz_meas, 'bo-', linewidth=2, markersize=10, label='Measured')\n",
        "    \n",
        "    # Theoretical\n",
        "    mode_viz_theory = np.concatenate([[0], mode_shapes_theory_norm[:, i]])\n",
        "    ax.plot(x_pos, mode_viz_theory, 'r^--', linewidth=2, markersize=10, alpha=0.7, label='Theoretical')\n",
        "    \n",
        "    ax.axhline(y=0, color='k', linestyle='-', alpha=0.3)\n",
        "    ax.set_xlabel('Position', fontsize=11)\n",
        "    ax.set_ylabel('Normalized Amplitude', fontsize=11)\n",
        "    ax.set_title(f'Mode {i+1}: {f_n_measured[i]:.2f} Hz (MAC={MAC[i,i]:.3f})', fontsize=12, fontweight='bold')\n",
        "    ax.set_xticks([0, 1, 2, 3])\n",
        "    ax.set_xticklabels(['Wall', 'm1', 'm2', 'm3'])\n",
        "    ax.legend(fontsize=10)\n",
        "    ax.grid(True, alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\nMode shape extraction complete!\")\n"
    ]
})

# Cell 12: Summary
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Summary: Modal Testing Results\n",
        "\n",
        "### Extracted Parameters\n",
        "\n",
        "**Natural Frequencies**:\n",
        "- Extracted from FFT peak picking\n",
        "- Typical accuracy: < 1% error with good data\n",
        "- Limited by frequency resolution (sampling rate / duration)\n",
        "\n",
        "**Damping Ratios**:\n",
        "- Method 1: Logarithmic decrement from decay\n",
        "- Method 2: Half-power bandwidth from FRF\n",
        "- Typical accuracy: 5-20% error (harder to measure)\n",
        "- Affected by: noise, nonlinearity, joint damping\n",
        "\n",
        "**Mode Shapes**:\n",
        "- Extracted from FRF amplitude ratios\n",
        "- Validated with MAC (Modal Assurance Criterion)\n",
        "- MAC > 0.9 indicates good correlation\n",
        "- Requires multi-point measurements\n",
        "\n",
        "### Key Takeaways\n",
        "\n",
        "1. **Hammer test is practical**: Quick, portable, broadband\n",
        "2. **FFT reveals all modes**: Peaks at natural frequencies\n",
        "3. **Multiple methods for damping**: Cross-validate results\n",
        "4. **MAC validates modes**: Quantifies correlation\n",
        "5. **Measurement matters**: Noise, resolution, duration affect accuracy\n",
        "\n",
        "### Real-World Applications\n",
        "\n",
        "**Aerospace**:\n",
        "- Aircraft structure validation\n",
        "- Flutter analysis\n",
        "- Component testing\n",
        "\n",
        "**Civil Engineering**:\n",
        "- Bridge health monitoring\n",
        "- Building dynamics\n",
        "- Earthquake response\n",
        "\n",
        "**Automotive**:\n",
        "- NVH (Noise, Vibration, Harshness)\n",
        "- Chassis dynamics\n",
        "- Component validation\n",
        "\n",
        "**Manufacturing**:\n",
        "- Machine tool dynamics\n",
        "- Quality control\n",
        "- Predictive maintenance\n",
        "\n",
        "### Further Reading\n",
        "\n",
        "- Ewins: \"Modal Testing: Theory, Practice, and Application\"\n",
        "- Avitabile: \"Experimental Modal Analysis\" course notes\n",
        "- Standards: ISO 7626 (Vibration testing)\n",
        "\n",
        "---\n",
        "\n",
        "## Congratulations!\n",
        "\n",
        "You've completed Unit 5: Rigid Body Kinetics & Vibrations\n",
        "\n",
        "Topics covered:\n",
        "- L1: Rigid body equations of motion\n",
        "- L2: Coupled translation-rotation systems\n",
        "- L3: Multi-DOF systems and chaos\n",
        "- L4: SDOF vibrations and damping\n",
        "- L5: MDOF modal analysis and FRF\n",
        "- P1: Experimental modal analysis\n",
        "\n",
        "Next: Unit 6 (Work & Energy Methods)\n",
        "\n",
        "---\n"
    ]
})

# Save notebook
os.makedirs(output_dir, exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("=" * 60)
print("Unit 5 Practical 1 Created Successfully!")
print("=" * 60)
print(f"\nFile: {output_path}")
print(f"\nNotebook structure:")
print(f"  Total cells: {len(notebook['cells'])}")
print(f"  Markdown: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'markdown')}")
print(f"  Code: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'code')}")
print(f"\nContent:")
print(f"  Part 1: Define unknown 3-DOF system")
print(f"  Part 2: Hammer test simulation")
print(f"  Part 3: FFT and peak picking")
print(f"  Part 4: Damping extraction")
print(f"  Part 5: Mode shape identification with MAC")
print(f"\nDuration: ~60 minutes")
print(f"\nReady to test!")
