"""
Create Unit 5 Lecture 3: 1-2 DOF Rigid Body Systems
Focus: Coupled dynamics, double pendulum, matrix formulation
Target: ~90 minutes comprehensive coverage
"""

import json
import os
import numpy as np

# Paths
output_dir = r"d:\Sunny\DSM\notebooks\Teacher"
output_path = os.path.join(output_dir, "T_U5_L3_Multi_DOF_Rigid_Body_Systems.ipynb")

# Create notebook structure
notebook = {
    "cells": [],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.14.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

# Cell 1: Header
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# Unit 5 Lecture 3: Multi-DOF Rigid Body Systems\n",
        "## Coupled Dynamics & Double Pendulum\n",
        "\n",
        "---\n",
        "\n",
        "### Learning Objectives\n",
        "By the end of this lecture, you will be able to:\n",
        "1. **Formulate equations** for systems with multiple degrees of freedom (DOF)\n",
        "2. **Derive coupled equations** using Lagrange or Newton-Euler methods\n",
        "3. **Write matrix form**: $\\mathbf{M}\\ddot{\\mathbf{q}} + \\mathbf{C}\\dot{\\mathbf{q}} + \\mathbf{K}\\mathbf{q} = \\mathbf{F}$\n",
        "4. **Analyze double pendulum** - classic chaotic system\n",
        "5. **Simulate coupled dynamics** numerically and interpret results\n",
        "\n",
        "### Context\n",
        "**From single DOF to multi-DOF:**\n",
        "- Lecture 1: Single rigid body → 1 DOF (pendulum, rolling wheel)\n",
        "- Lecture 2: Coupled translation-rotation → constraints reduce DOF\n",
        "- **This lecture**: Multiple bodies, multiple DOF → coupled equations\n",
        "\n",
        "**Why multi-DOF matters**:\n",
        "- Real systems: Robot arms (6+ DOF), vehicles (3+ DOF), structures\n",
        "- Coupling: Motion of one body affects others\n",
        "- Complexity: Can exhibit chaos (double pendulum!)\n",
        "- Foundation: Bridge to vibrations (Unit 5.2)\n",
        "\n",
        "### Key Concepts\n",
        "**Degrees of Freedom (DOF)**: Number of independent coordinates needed\n",
        "- 2 masses on springs: 2 DOF (x₁, x₂)\n",
        "- Double pendulum: 2 DOF (θ₁, θ₂)\n",
        "- Rigid body in 3D: 6 DOF (3 translation + 3 rotation)\n",
        "\n",
        "**Matrix formulation**: Compact representation\n",
        "$$\\mathbf{M}\\ddot{\\mathbf{q}} + \\mathbf{C}\\dot{\\mathbf{q}} + \\mathbf{K}\\mathbf{q} = \\mathbf{F}$$\n",
        "- $\\mathbf{M}$ = mass/inertia matrix\n",
        "- $\\mathbf{C}$ = damping matrix\n",
        "- $\\mathbf{K}$ = stiffness matrix\n",
        "- $\\mathbf{q}$ = generalized coordinates\n",
        "\n",
        "---\n"
    ]
})

# Cell 2: Imports
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Import libraries\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from matplotlib.animation import FuncAnimation\n",
        "from matplotlib.patches import Circle\n",
        "from scipy.integrate import odeint\n",
        "from IPython.display import HTML\n",
        "\n",
        "# Plotting style\n",
        "plt.style.use('seaborn-v0_8-darkgrid')\n",
        "plt.rcParams['figure.figsize'] = (12, 4)\n",
        "\n",
        "print(\"Libraries imported successfully!\")\n",
        "print(\"  Ready for multi-DOF analysis...\")\n"
    ]
})

# Cell 3: Two-Mass-Spring Theory
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part A: Two Masses Connected by Springs \n",
        "\n",
        "### Setup\n",
        "**System**: Two masses (m₁, m₂) connected by springs (k₁, k₂, k₃)\n",
        "```\n",
        "Wall--[k₁]--[m₁]--[k₂]--[m₂]--[k₃]--Wall\n",
        "```\n",
        "\n",
        "**Degrees of freedom**: 2 (positions x₁, x₂)\n",
        "\n",
        "### Equations of Motion\n",
        "\n",
        "**Free body diagrams**:\n",
        "- Mass 1: Forces from k₁ (left), k₂ (right)\n",
        "- Mass 2: Forces from k₂ (left), k₃ (right)\n",
        "\n",
        "**Newton's 2nd Law**:\n",
        "$$m_1 \\ddot{x}_1 = -k_1 x_1 + k_2(x_2 - x_1)$$\n",
        "$$m_2 \\ddot{x}_2 = -k_2(x_2 - x_1) - k_3 x_2$$\n",
        "\n",
        "Rearrange:\n",
        "$$m_1 \\ddot{x}_1 + (k_1 + k_2)x_1 - k_2 x_2 = 0$$\n",
        "$$m_2 \\ddot{x}_2 - k_2 x_1 + (k_2 + k_3)x_2 = 0$$\n",
        "\n",
        "### Matrix Form\n",
        "\n",
        "$$\\begin{bmatrix} m_1 & 0 \\\\ 0 & m_2 \\end{bmatrix} \\begin{bmatrix} \\ddot{x}_1 \\\\ \\ddot{x}_2 \\end{bmatrix} + \\begin{bmatrix} k_1+k_2 & -k_2 \\\\ -k_2 & k_2+k_3 \\end{bmatrix} \\begin{bmatrix} x_1 \\\\ x_2 \\end{bmatrix} = \\begin{bmatrix} 0 \\\\ 0 \\end{bmatrix}$$\n",
        "\n",
        "**Compact form**:\n",
        "$$\\mathbf{M}\\ddot{\\mathbf{x}} + \\mathbf{K}\\mathbf{x} = \\mathbf{0}$$\n",
        "\n",
        "### Natural Frequencies (Eigenvalue Problem)\n",
        "\n",
        "Assume solution: $\\mathbf{x} = \\mathbf{X}e^{i\\omega t}$\n",
        "\n",
        "Substitute:\n",
        "$$(-\\omega^2 \\mathbf{M} + \\mathbf{K})\\mathbf{X} = \\mathbf{0}$$\n",
        "\n",
        "**Eigenvalue problem**:\n",
        "$$\\det(\\mathbf{K} - \\omega^2 \\mathbf{M}) = 0$$\n",
        "\n",
        "Solutions give:\n",
        "- **Natural frequencies**: $\\omega_1, \\omega_2$ (eigenvalues)\n",
        "- **Mode shapes**: $\\mathbf{X}_1, \\mathbf{X}_2$ (eigenvectors)\n",
        "\n",
        "### Physical Interpretation\n",
        "\n",
        "**Mode 1** (lower frequency): Masses move in same direction\n",
        "- \"Breathing mode\" - springs stretch/compress together\n",
        "\n",
        "**Mode 2** (higher frequency): Masses move in opposite directions\n",
        "- \"Sloshing mode\" - middle spring (k₂) does most work\n",
        "\n",
        "**General motion**: Superposition of both modes!\n",
        "\n",
        "---\n"
    ]
})

# Cell 4: Two-Mass-Spring Simulation
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 1: Two Masses with Three Springs\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 1: Coupled Mass-Spring System\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "m1 = 1.0  # kg\n",
        "m2 = 1.5  # kg\n",
        "k1 = 100.0  # N/m (left spring)\n",
        "k2 = 150.0  # N/m (middle spring - coupling)\n",
        "k3 = 100.0  # N/m (right spring)\n",
        "\n",
        "# Mass and stiffness matrices\n",
        "M = np.array([[m1, 0], [0, m2]])\n",
        "K = np.array([[k1 + k2, -k2], [-k2, k2 + k3]])\n",
        "\n",
        "print(f\"\\nSystem Properties:\")\n",
        "print(f\"  m₁ = {m1} kg, m₂ = {m2} kg\")\n",
        "print(f\"  k₁ = {k1} N/m, k₂ = {k2} N/m (coupling), k₃ = {k3} N/m\")\n",
        "print(f\"\\nMass Matrix M:\")\n",
        "print(M)\n",
        "print(f\"\\nStiffness Matrix K:\")\n",
        "print(K)\n",
        "\n",
        "# Solve eigenvalue problem: K·X = ω²·M·X\n",
        "# Convert to standard form: M⁻¹·K·X = ω²·X\n",
        "M_inv = np.linalg.inv(M)\n",
        "A = M_inv @ K\n",
        "\n",
        "eigenvalues, eigenvectors = np.linalg.eig(A)\n",
        "omega_n = np.sqrt(eigenvalues)  # Natural frequencies\n",
        "mode_shapes = eigenvectors  # Mode shapes\n",
        "\n",
        "# Sort by frequency\n",
        "idx = np.argsort(omega_n)\n",
        "omega_n = omega_n[idx]\n",
        "mode_shapes = mode_shapes[:, idx]\n",
        "\n",
        "print(f\"\\nNatural Frequencies:\")\n",
        "print(f\"  ω₁ = {omega_n[0]:.3f} rad/s = {omega_n[0]/(2*np.pi):.3f} Hz (Mode 1)\")\n",
        "print(f\"  ω₂ = {omega_n[1]:.3f} rad/s = {omega_n[1]/(2*np.pi):.3f} Hz (Mode 2)\")\n",
        "print(f\"  Ratio ω₂/ω₁ = {omega_n[1]/omega_n[0]:.3f}\")\n",
        "\n",
        "print(f\"\\nMode Shapes (normalized):\")\n",
        "# Normalize so first element is 1\n",
        "mode1 = mode_shapes[:, 0] / mode_shapes[0, 0]\n",
        "mode2 = mode_shapes[:, 1] / mode_shapes[0, 1]\n",
        "print(f\"  Mode 1: [{mode1[0]:.3f}, {mode1[1]:.3f}] - Same direction\")\n",
        "print(f\"  Mode 2: [{mode2[0]:.3f}, {mode2[1]:.3f}] - Opposite directions\")\n",
        "\n",
        "# Simulate system with ODE\n",
        "def system_ode(y, t):\n",
        "    \"\"\"State: y = [x1, v1, x2, v2]\"\"\"\n",
        "    x1, v1, x2, v2 = y\n",
        "    \n",
        "    # Accelerations from equations of motion\n",
        "    a1 = -(k1 + k2) * x1 / m1 + k2 * x2 / m1\n",
        "    a2 = k2 * x1 / m2 - (k2 + k3) * x2 / m2\n",
        "    \n",
        "    return [v1, a1, v2, a2]\n",
        "\n",
        "# Initial conditions: Displace m1, release from rest\n",
        "x1_0 = 0.1  # m\n",
        "x2_0 = 0.0  # m\n",
        "y0 = [x1_0, 0, x2_0, 0]\n",
        "\n",
        "# Time array\n",
        "t = np.linspace(0, 5, 1000)\n",
        "\n",
        "# Solve\n",
        "solution = odeint(system_ode, y0, t)\n",
        "x1 = solution[:, 0]\n",
        "v1 = solution[:, 1]\n",
        "x2 = solution[:, 2]\n",
        "v2 = solution[:, 3]\n",
        "\n",
        "# Energy\n",
        "KE = 0.5 * m1 * v1**2 + 0.5 * m2 * v2**2\n",
        "PE = 0.5 * k1 * x1**2 + 0.5 * k2 * (x2 - x1)**2 + 0.5 * k3 * x2**2\n",
        "E_total = KE + PE\n",
        "\n",
        "# Plotting\n",
        "fig, axes = plt.subplots(2, 3, figsize=(16, 10))\n",
        "\n",
        "# Positions\n",
        "ax1 = axes[0, 0]\n",
        "ax1.plot(t, x1*100, 'b-', linewidth=2, label='Mass 1')\n",
        "ax1.plot(t, x2*100, 'r-', linewidth=2, label='Mass 2')\n",
        "ax1.set_xlabel('Time (s)', fontsize=11)\n",
        "ax1.set_ylabel('Position (cm)', fontsize=11)\n",
        "ax1.set_title('Positions vs Time', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=10)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Phase portraits\n",
        "ax2 = axes[0, 1]\n",
        "ax2.plot(x1*100, v1*100, 'b-', linewidth=2, alpha=0.7)\n",
        "ax2.plot(x1[0]*100, v1[0]*100, 'go', markersize=10, label='Start')\n",
        "ax2.set_xlabel('x₁ (cm)', fontsize=11)\n",
        "ax2.set_ylabel('v₁ (cm/s)', fontsize=11)\n",
        "ax2.set_title('Phase Portrait: Mass 1', fontsize=12, fontweight='bold')\n",
        "ax2.legend(fontsize=10)\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "ax3 = axes[0, 2]\n",
        "ax3.plot(x2*100, v2*100, 'r-', linewidth=2, alpha=0.7)\n",
        "ax3.plot(x2[0]*100, v2[0]*100, 'go', markersize=10, label='Start')\n",
        "ax3.set_xlabel('x₂ (cm)', fontsize=11)\n",
        "ax3.set_ylabel('v₂ (cm/s)', fontsize=11)\n",
        "ax3.set_title('Phase Portrait: Mass 2', fontsize=12, fontweight='bold')\n",
        "ax3.legend(fontsize=10)\n",
        "ax3.grid(True, alpha=0.3)\n",
        "\n",
        "# Energy\n",
        "ax4 = axes[1, 0]\n",
        "ax4.plot(t, KE, 'b-', linewidth=2, label='KE')\n",
        "ax4.plot(t, PE, 'r-', linewidth=2, label='PE')\n",
        "ax4.plot(t, E_total, 'k--', linewidth=2, label='Total')\n",
        "ax4.set_xlabel('Time (s)', fontsize=11)\n",
        "ax4.set_ylabel('Energy (J)', fontsize=11)\n",
        "ax4.set_title('Energy vs Time', fontsize=12, fontweight='bold')\n",
        "ax4.legend(fontsize=10)\n",
        "ax4.grid(True, alpha=0.3)\n",
        "\n",
        "# Mode shapes visualization\n",
        "ax5 = axes[1, 1]\n",
        "x_pos = np.array([0, 1, 2])  # Wall, m1, m2 positions\n",
        "mode1_viz = np.array([0, mode1[0], mode1[1]])\n",
        "mode2_viz = np.array([0, mode2[0], mode2[1]])\n",
        "ax5.plot(x_pos, mode1_viz, 'bo-', linewidth=2.5, markersize=12, label=f'Mode 1 ({omega_n[0]:.2f} rad/s)')\n",
        "ax5.plot(x_pos, mode2_viz, 'rs-', linewidth=2.5, markersize=12, label=f'Mode 2 ({omega_n[1]:.2f} rad/s)')\n",
        "ax5.axhline(y=0, color='k', linestyle='--', alpha=0.3)\n",
        "ax5.set_xlabel('Position along system', fontsize=11)\n",
        "ax5.set_ylabel('Normalized Amplitude', fontsize=11)\n",
        "ax5.set_title('Mode Shapes', fontsize=12, fontweight='bold')\n",
        "ax5.set_xticks(x_pos)\n",
        "ax5.set_xticklabels(['Wall', 'm₁', 'm₂'])\n",
        "ax5.legend(fontsize=10)\n",
        "ax5.grid(True, alpha=0.3)\n",
        "\n",
        "# Configuration space\n",
        "ax6 = axes[1, 2]\n",
        "ax6.plot(x1*100, x2*100, 'purple', linewidth=2, alpha=0.7)\n",
        "ax6.plot(x1[0]*100, x2[0]*100, 'go', markersize=10, label='Start')\n",
        "ax6.set_xlabel('x₁ (cm)', fontsize=11)\n",
        "ax6.set_ylabel('x₂ (cm)', fontsize=11)\n",
        "ax6.set_title('Configuration Space', fontsize=12, fontweight='bold')\n",
        "ax6.legend(fontsize=10)\n",
        "ax6.grid(True, alpha=0.3)\n",
        "ax6.set_aspect('equal')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f\"\\nEnergy conservation: {E_total[0]:.6f} → {E_total[-1]:.6f} J\")\n",
        "print(f\"\\nKey observations:\")\n",
        "print(f\"  1. Mode 1: Both masses oscillate together (lower frequency)\")\n",
        "print(f\"  2. Mode 2: Masses oscillate oppositely (higher frequency)\")\n",
        "print(f\"  3. Actual motion: Combination of both modes!\")\n"
    ]
})

# Cell 5: Double Pendulum Theory
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part B: Double Pendulum \n",
        "\n",
        "### Setup\n",
        "**System**: Two pendulums connected end-to-end\n",
        "- Mass 1 (m₁) at end of rod 1 (length L₁)\n",
        "- Mass 2 (m₂) at end of rod 2 (length L₂), attached to m₁\n",
        "- **2 DOF**: angles θ₁, θ₂ (measured from vertical)\n",
        "\n",
        "### Why is this special?\n",
        "- **Chaotic dynamics!** Small changes in initial conditions → vastly different trajectories\n",
        "- **Nonlinear coupling**: Equations have sin/cos products\n",
        "- **No general solution**: Must solve numerically\n",
        "\n",
        "### Equations of Motion (Lagrangian)\n",
        "\n",
        "**Positions** (Cartesian):\n",
        "$$x_1 = L_1 \\sin\\theta_1, \\quad y_1 = -L_1 \\cos\\theta_1$$\n",
        "$$x_2 = L_1 \\sin\\theta_1 + L_2 \\sin\\theta_2, \\quad y_2 = -L_1 \\cos\\theta_1 - L_2 \\cos\\theta_2$$\n",
        "\n",
        "**Kinetic energy**:\n",
        "$$T = \\frac{1}{2}m_1(\\dot{x}_1^2 + \\dot{y}_1^2) + \\frac{1}{2}m_2(\\dot{x}_2^2 + \\dot{y}_2^2)$$\n",
        "\n",
        "After differentiation:\n",
        "$$T = \\frac{1}{2}(m_1 + m_2)L_1^2\\dot{\\theta}_1^2 + \\frac{1}{2}m_2 L_2^2\\dot{\\theta}_2^2 + m_2 L_1 L_2 \\dot{\\theta}_1\\dot{\\theta}_2\\cos(\\theta_1 - \\theta_2)$$\n",
        "\n",
        "**Potential energy**:\n",
        "$$V = m_1 g y_1 + m_2 g y_2 = -(m_1 + m_2)g L_1 \\cos\\theta_1 - m_2 g L_2 \\cos\\theta_2$$\n",
        "\n",
        "**Lagrange equations**: $\\frac{d}{dt}\\frac{\\partial L}{\\partial \\dot{\\theta}_i} - \\frac{\\partial L}{\\partial \\theta_i} = 0$\n",
        "\n",
        "**Result** (complex!):\n",
        "$$(m_1 + m_2)L_1^2\\ddot{\\theta}_1 + m_2 L_1 L_2 \\ddot{\\theta}_2\\cos(\\theta_1-\\theta_2) + m_2 L_1 L_2 \\dot{\\theta}_2^2\\sin(\\theta_1-\\theta_2) + (m_1+m_2)g L_1\\sin\\theta_1 = 0$$\n",
        "\n",
        "$$m_2 L_2^2\\ddot{\\theta}_2 + m_2 L_1 L_2 \\ddot{\\theta}_1\\cos(\\theta_1-\\theta_2) - m_2 L_1 L_2 \\dot{\\theta}_1^2\\sin(\\theta_1-\\theta_2) + m_2 g L_2\\sin\\theta_2 = 0$$\n",
        "\n",
        "### Key Features\n",
        "\n",
        "**Nonlinear terms**:\n",
        "- $\\dot{\\theta}_1^2\\sin(\\theta_1-\\theta_2)$ → centrifugal-like effect\n",
        "- $\\cos(\\theta_1-\\theta_2)$ → coupling depends on relative angle!\n",
        "\n",
        "**Small angle approximation** ($\\sin\\theta \\approx \\theta$, $\\cos\\theta \\approx 1$):\n",
        "- System becomes linear (like two-mass-spring)\n",
        "- Has normal modes, predictable oscillations\n",
        "- **Large angles**: Nonlinearity → chaos!\n",
        "\n",
        "**Sensitivity to initial conditions**:\n",
        "- Two pendulums starting 0.001° apart → completely different after ~10s\n",
        "- This is **deterministic chaos**: equations known, but long-term prediction impossible\n",
        "\n",
        "---\n"
    ]
})

# Cell 6: Double Pendulum Simulation
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 2: Double Pendulum - Chaotic Motion\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 2: Double Pendulum Dynamics\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "m1 = 1.0  # kg\n",
        "m2 = 1.0  # kg\n",
        "L1 = 1.0  # m\n",
        "L2 = 1.0  # m\n",
        "g = 9.81  # m/s^2\n",
        "\n",
        "print(f\"\\nDouble Pendulum Properties:\")\n",
        "print(f\"  m₁ = {m1} kg, L₁ = {L1} m\")\n",
        "print(f\"  m₂ = {m2} kg, L₂ = {L2} m\")\n",
        "\n",
        "def double_pendulum_ode(y, t, m1, m2, L1, L2, g):\n",
        "    \"\"\"\n",
        "    Double pendulum equations of motion\n",
        "    State: y = [θ₁, ω₁, θ₂, ω₂]\n",
        "    \"\"\"\n",
        "    theta1, omega1, theta2, omega2 = y\n",
        "    \n",
        "    # Precompute common terms\n",
        "    delta = theta2 - theta1\n",
        "    den1 = (m1 + m2) * L1 - m2 * L1 * np.cos(delta) * np.cos(delta)\n",
        "    den2 = (L2 / L1) * den1\n",
        "    \n",
        "    # Angular accelerations (from solving coupled equations)\n",
        "    alpha1 = (m2 * L1 * omega1**2 * np.sin(delta) * np.cos(delta)\n",
        "              + m2 * g * np.sin(theta2) * np.cos(delta)\n",
        "              + m2 * L2 * omega2**2 * np.sin(delta)\n",
        "              - (m1 + m2) * g * np.sin(theta1)) / den1\n",
        "    \n",
        "    alpha2 = (-m2 * L2 * omega2**2 * np.sin(delta) * np.cos(delta)\n",
        "              + (m1 + m2) * g * np.sin(theta1) * np.cos(delta)\n",
        "              - (m1 + m2) * L1 * omega1**2 * np.sin(delta)\n",
        "              - (m1 + m2) * g * np.sin(theta2)) / den2\n",
        "    \n",
        "    return [omega1, alpha1, omega2, alpha2]\n",
        "\n",
        "# Initial conditions (degrees converted to radians)\n",
        "theta1_0 = np.radians(120)  # Start at 120 degrees\n",
        "theta2_0 = np.radians(90)   # 90 degrees\n",
        "y0 = [theta1_0, 0, theta2_0, 0]  # Released from rest\n",
        "\n",
        "# Time array\n",
        "t = np.linspace(0, 20, 5000)  # 20 seconds, high resolution\n",
        "\n",
        "# Solve\n",
        "print(\"\\n⏳ Simulating (this may take a moment)...\")\n",
        "solution = odeint(double_pendulum_ode, y0, t, args=(m1, m2, L1, L2, g))\n",
        "theta1 = solution[:, 0]\n",
        "omega1 = solution[:, 1]\n",
        "theta2 = solution[:, 2]\n",
        "omega2 = solution[:, 3]\n",
        "\n",
        "# Cartesian positions for plotting\n",
        "x1 = L1 * np.sin(theta1)\n",
        "y1 = -L1 * np.cos(theta1)\n",
        "x2 = x1 + L2 * np.sin(theta2)\n",
        "y2 = y1 - L2 * np.cos(theta2)\n",
        "\n",
        "# Energy\n",
        "v1_x = L1 * omega1 * np.cos(theta1)\n",
        "v1_y = L1 * omega1 * np.sin(theta1)\n",
        "v2_x = v1_x + L2 * omega2 * np.cos(theta2)\n",
        "v2_y = v1_y + L2 * omega2 * np.sin(theta2)\n",
        "\n",
        "KE = 0.5 * m1 * (v1_x**2 + v1_y**2) + 0.5 * m2 * (v2_x**2 + v2_y**2)\n",
        "PE = m1 * g * y1 + m2 * g * y2\n",
        "E_total = KE + PE\n",
        "\n",
        "print(\"Simulation complete!\")\n",
        "\n",
        "# Plotting\n",
        "fig = plt.figure(figsize=(16, 12))\n",
        "\n",
        "# Trajectory of bob 2\n",
        "ax1 = plt.subplot(2, 3, 1)\n",
        "ax1.plot(x2, y2, 'purple', linewidth=0.5, alpha=0.7)\n",
        "ax1.plot(x2[0], y2[0], 'go', markersize=10, label='Start')\n",
        "ax1.plot(x2[-1], y2[-1], 'ro', markersize=10, label='End (20s)')\n",
        "ax1.plot(0, 0, 'ko', markersize=8, label='Pivot')\n",
        "# Draw circle showing maximum reach\n",
        "circle = plt.Circle((0, 0), L1 + L2, fill=False, color='gray', linestyle='--', alpha=0.3)\n",
        "ax1.add_patch(circle)\n",
        "ax1.set_xlim([-(L1+L2)*1.1, (L1+L2)*1.1])\n",
        "ax1.set_ylim([-(L1+L2)*1.1, (L1+L2)*1.1])\n",
        "ax1.set_aspect('equal')\n",
        "ax1.set_xlabel('x (m)', fontsize=11)\n",
        "ax1.set_ylabel('y (m)', fontsize=11)\n",
        "ax1.set_title('Trajectory of Bob 2 (Chaotic!)', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=9)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Angles vs time\n",
        "ax2 = plt.subplot(2, 3, 2)\n",
        "ax2.plot(t, np.degrees(theta1), 'b-', linewidth=1.5, label='θ₁')\n",
        "ax2.plot(t, np.degrees(theta2), 'r-', linewidth=1.5, label='θ₂')\n",
        "ax2.set_xlabel('Time (s)', fontsize=11)\n",
        "ax2.set_ylabel('Angle (degrees)', fontsize=11)\n",
        "ax2.set_title('Angles vs Time', fontsize=12, fontweight='bold')\n",
        "ax2.legend(fontsize=10)\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "# Angular velocities\n",
        "ax3 = plt.subplot(2, 3, 3)\n",
        "ax3.plot(t, omega1, 'b-', linewidth=1.5, label='ω₁')\n",
        "ax3.plot(t, omega2, 'r-', linewidth=1.5, label='ω₂')\n",
        "ax3.set_xlabel('Time (s)', fontsize=11)\n",
        "ax3.set_ylabel('Angular Velocity (rad/s)', fontsize=11)\n",
        "ax3.set_title('Angular Velocities vs Time', fontsize=12, fontweight='bold')\n",
        "ax3.legend(fontsize=10)\n",
        "ax3.grid(True, alpha=0.3)\n",
        "\n",
        "# Phase portrait: θ₁ vs ω₁\n",
        "ax4 = plt.subplot(2, 3, 4)\n",
        "ax4.plot(np.degrees(theta1), omega1, 'b-', linewidth=0.5, alpha=0.7)\n",
        "ax4.plot(np.degrees(theta1[0]), omega1[0], 'go', markersize=10, label='Start')\n",
        "ax4.set_xlabel('θ₁ (degrees)', fontsize=11)\n",
        "ax4.set_ylabel('ω₁ (rad/s)', fontsize=11)\n",
        "ax4.set_title('Phase Portrait: Pendulum 1', fontsize=12, fontweight='bold')\n",
        "ax4.legend(fontsize=10)\n",
        "ax4.grid(True, alpha=0.3)\n",
        "\n",
        "# Phase portrait: θ₂ vs ω₂\n",
        "ax5 = plt.subplot(2, 3, 5)\n",
        "ax5.plot(np.degrees(theta2), omega2, 'r-', linewidth=0.5, alpha=0.7)\n",
        "ax5.plot(np.degrees(theta2[0]), omega2[0], 'go', markersize=10, label='Start')\n",
        "ax5.set_xlabel('θ₂ (degrees)', fontsize=11)\n",
        "ax5.set_ylabel('ω₂ (rad/s)', fontsize=11)\n",
        "ax5.set_title('Phase Portrait: Pendulum 2', fontsize=12, fontweight='bold')\n",
        "ax5.legend(fontsize=10)\n",
        "ax5.grid(True, alpha=0.3)\n",
        "\n",
        "# Energy\n",
        "ax6 = plt.subplot(2, 3, 6)\n",
        "ax6.plot(t, KE, 'b-', linewidth=1.5, label='KE')\n",
        "ax6.plot(t, PE, 'r-', linewidth=1.5, label='PE')\n",
        "ax6.plot(t, E_total, 'k--', linewidth=2, label='Total')\n",
        "ax6.set_xlabel('Time (s)', fontsize=11)\n",
        "ax6.set_ylabel('Energy (J)', fontsize=11)\n",
        "ax6.set_title('Energy (Conservation Check)', fontsize=12, fontweight='bold')\n",
        "ax6.legend(fontsize=10)\n",
        "ax6.grid(True, alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f\"\\nStatistics:\")\n",
        "print(f\"  Energy conservation: {E_total[0]:.6f} → {E_total[-1]:.6f} J\")\n",
        "print(f\"  Error: {abs(E_total[-1] - E_total[0])/E_total[0]*100:.4f}%\")\n",
        "print(f\"  Max ω₁: {np.max(np.abs(omega1)):.2f} rad/s\")\n",
        "print(f\"  Max ω₂: {np.max(np.abs(omega2)):.2f} rad/s\")\n",
        "\n",
        "print(f\"\\nChaos characteristics:\")\n",
        "print(f\"  1. Trajectory: Complex, never repeats exactly\")\n",
        "print(f\"  2. Phase portraits: Fill space (not simple loops)\")\n",
        "print(f\"  3. Energy exchanges wildly between pendulums\")\n",
        "print(f\"  4. Small IC change → completely different motion!\")\n"
    ]
})

# Cell 7: Chaos Demonstration
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 3: Sensitivity to Initial Conditions (Chaos)\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 3: Demonstrating Chaos - Butterfly Effect\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Two nearly identical initial conditions\n",
        "theta1_0_A = np.radians(120.0)  # Case A\n",
        "theta1_0_B = np.radians(120.01)  # Case B - just 0.01° different!\n",
        "theta2_0 = np.radians(90)\n",
        "\n",
        "y0_A = [theta1_0_A, 0, theta2_0, 0]\n",
        "y0_B = [theta1_0_B, 0, theta2_0, 0]\n",
        "\n",
        "print(f\"\\nInitial Conditions:\")\n",
        "print(f\"  Case A: θ₁ = {np.degrees(theta1_0_A):.4f}°\")\n",
        "print(f\"  Case B: θ₁ = {np.degrees(theta1_0_B):.4f}°\")\n",
        "print(f\"  Difference: {np.degrees(theta1_0_B - theta1_0_A):.4f}° (tiny!)\")\n",
        "\n",
        "# Simulate both\n",
        "t_chaos = np.linspace(0, 15, 3000)\n",
        "\n",
        "print(\"\\n⏳ Simulating both cases...\")\n",
        "sol_A = odeint(double_pendulum_ode, y0_A, t_chaos, args=(m1, m2, L1, L2, g))\n",
        "sol_B = odeint(double_pendulum_ode, y0_B, t_chaos, args=(m1, m2, L1, L2, g))\n",
        "\n",
        "theta1_A = sol_A[:, 0]\n",
        "theta2_A = sol_A[:, 2]\n",
        "theta1_B = sol_B[:, 0]\n",
        "theta2_B = sol_B[:, 2]\n",
        "\n",
        "# Calculate difference (divergence)\n",
        "diff_theta1 = np.degrees(np.abs(theta1_A - theta1_B))\n",
        "diff_theta2 = np.degrees(np.abs(theta2_A - theta2_B))\n",
        "\n",
        "# Positions for trajectory comparison\n",
        "x2_A = L1 * np.sin(theta1_A) + L2 * np.sin(theta2_A)\n",
        "y2_A = -L1 * np.cos(theta1_A) - L2 * np.cos(theta2_A)\n",
        "x2_B = L1 * np.sin(theta1_B) + L2 * np.sin(theta2_B)\n",
        "y2_B = -L1 * np.cos(theta1_B) - L2 * np.cos(theta2_B)\n",
        "\n",
        "print(\"Simulations complete!\")\n",
        "\n",
        "# Plotting\n",
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
        "\n",
        "# Angle comparison: θ₁\n",
        "ax1 = axes[0, 0]\n",
        "ax1.plot(t_chaos, np.degrees(theta1_A), 'b-', linewidth=1.5, label='Case A', alpha=0.8)\n",
        "ax1.plot(t_chaos, np.degrees(theta1_B), 'r--', linewidth=1.5, label='Case B', alpha=0.8)\n",
        "ax1.set_xlabel('Time (s)', fontsize=11)\n",
        "ax1.set_ylabel('θ₁ (degrees)', fontsize=11)\n",
        "ax1.set_title('Angle θ₁: Divergence Over Time', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=10)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Angle comparison: θ₂\n",
        "ax2 = axes[0, 1]\n",
        "ax2.plot(t_chaos, np.degrees(theta2_A), 'b-', linewidth=1.5, label='Case A', alpha=0.8)\n",
        "ax2.plot(t_chaos, np.degrees(theta2_B), 'r--', linewidth=1.5, label='Case B', alpha=0.8)\n",
        "ax2.set_xlabel('Time (s)', fontsize=11)\n",
        "ax2.set_ylabel('θ₂ (degrees)', fontsize=11)\n",
        "ax2.set_title('Angle θ₂: Divergence Over Time', fontsize=12, fontweight='bold')\n",
        "ax2.legend(fontsize=10)\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "# Divergence (log scale)\n",
        "ax3 = axes[1, 0]\n",
        "ax3.semilogy(t_chaos, diff_theta1 + 1e-6, 'b-', linewidth=2, label='|Δθ₁|')\n",
        "ax3.semilogy(t_chaos, diff_theta2 + 1e-6, 'r-', linewidth=2, label='|Δθ₂|')\n",
        "ax3.axhline(y=0.01, color='g', linestyle='--', alpha=0.5, label='Initial diff')\n",
        "ax3.set_xlabel('Time (s)', fontsize=11)\n",
        "ax3.set_ylabel('Angular Difference (degrees, log scale)', fontsize=11)\n",
        "ax3.set_title('Exponential Divergence (Chaos!)', fontsize=12, fontweight='bold')\n",
        "ax3.legend(fontsize=10)\n",
        "ax3.grid(True, alpha=0.3, which='both')\n",
        "\n",
        "# Trajectory comparison\n",
        "ax4 = axes[1, 1]\n",
        "ax4.plot(x2_A, y2_A, 'b-', linewidth=0.8, alpha=0.6, label='Case A')\n",
        "ax4.plot(x2_B, y2_B, 'r-', linewidth=0.8, alpha=0.6, label='Case B')\n",
        "ax4.plot(0, 0, 'ko', markersize=8, label='Pivot')\n",
        "ax4.set_xlim([-(L1+L2)*1.1, (L1+L2)*1.1])\n",
        "ax4.set_ylim([-(L1+L2)*1.1, (L1+L2)*1.1])\n",
        "ax4.set_aspect('equal')\n",
        "ax4.set_xlabel('x (m)', fontsize=11)\n",
        "ax4.set_ylabel('y (m)', fontsize=11)\n",
        "ax4.set_title('Trajectories: Completely Different!', fontsize=12, fontweight='bold')\n",
        "ax4.legend(fontsize=10)\n",
        "ax4.grid(True, alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Find when difference exceeds certain thresholds\n",
        "idx_1deg = np.where(diff_theta1 > 1.0)[0]\n",
        "idx_10deg = np.where(diff_theta1 > 10.0)[0]\n",
        "idx_90deg = np.where(diff_theta1 > 90.0)[0]\n",
        "\n",
        "print(f\"\\n⏱Time to divergence:\")\n",
        "if len(idx_1deg) > 0:\n",
        "    print(f\"  1° difference: {t_chaos[idx_1deg[0]]:.2f} s\")\n",
        "if len(idx_10deg) > 0:\n",
        "    print(f\"  10° difference: {t_chaos[idx_10deg[0]]:.2f} s\")\n",
        "if len(idx_90deg) > 0:\n",
        "    print(f\"  90° difference: {t_chaos[idx_90deg[0]]:.2f} s\")\n",
        "\n",
        "print(f\"\\nButterfly Effect Demonstrated!\")\n",
        "print(f\"  Initial: 0.01° apart\")\n",
        "print(f\"  After {t_chaos[-1]:.0f}s: Completely uncorrelated!\")\n",
        "print(f\"\\nThis is deterministic chaos:\")\n",
        "print(f\"  - Equations are known (no randomness)\")\n",
        "print(f\"  - But long-term prediction impossible\")\n",
        "print(f\"  - Tiny errors grow exponentially\")\n"
    ]
})

# Cell 8: Summary
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Summary\n",
        "\n",
        "### Key Concepts\n",
        "\n",
        "**1. Multi-DOF Systems**\n",
        "- **Degrees of Freedom**: Number of independent coordinates\n",
        "- **Coupled equations**: Motion of one DOF affects others\n",
        "- **Matrix form**: $\\mathbf{M}\\ddot{\\mathbf{q}} + \\mathbf{C}\\dot{\\mathbf{q}} + \\mathbf{K}\\mathbf{q} = \\mathbf{F}$\n",
        "\n",
        "**2. Two-Mass-Spring System**\n",
        "- Linear coupling through springs\n",
        "- **Normal modes**: Special patterns where both masses oscillate at same frequency\n",
        "- **Eigenvalue problem**: $\\det(\\mathbf{K} - \\omega^2\\mathbf{M}) = 0$\n",
        "- Natural frequencies: $\\omega_1, \\omega_2$\n",
        "- Mode shapes: How masses move relative to each other\n",
        "\n",
        "**3. Double Pendulum**\n",
        "- **Nonlinear coupling**: Equations have $\\sin(\\theta_1 - \\theta_2)$ terms\n",
        "- **Chaotic dynamics**: Sensitive to initial conditions\n",
        "- **Butterfly effect**: 0.01° difference → completely different after ~10s\n",
        "- **Energy exchange**: Irregular transfer between pendulums\n",
        "\n",
        "### Problem-Solving Strategy\n",
        "\n",
        "**For coupled systems**:\n",
        "1. **Identify DOF**: Count independent coordinates\n",
        "2. **Choose coordinates**: Generalized coordinates (angles, positions)\n",
        "3. **Derive equations**:\n",
        "   - **Newton-Euler**: FBD for each body, write ΣF = ma and Στ = Iα\n",
        "   - **Lagrange**: $L = T - V$, then $\\frac{d}{dt}\\frac{\\partial L}{\\partial \\dot{q}_i} - \\frac{\\partial L}{\\partial q_i} = 0$\n",
        "4. **Write matrix form**: Identify $\\mathbf{M}$, $\\mathbf{K}$, $\\mathbf{C}$ matrices\n",
        "5. **Solve**:\n",
        "   - **Linear**: Eigenvalue problem for modes\n",
        "   - **Nonlinear**: Numerical integration (odeint)\n",
        "\n",
        "### Physical Insights\n",
        "\n",
        "**Normal modes** (linear systems):\n",
        "- System oscillates with single frequency\n",
        "- All parts move in fixed ratio (mode shape)\n",
        "- General motion = superposition of modes\n",
        "\n",
        "**Chaos** (nonlinear systems):\n",
        "- Long-term unpredictability despite deterministic equations\n",
        "- Sensitive dependence on initial conditions\n",
        "- Common in nature: weather, turbulence, solar system\n",
        "\n",
        "### Design Implications\n",
        "\n",
        "- **Vibration control**: Design to avoid resonances (match frequencies)\n",
        "- **Robots**: Account for coupling when controlling multiple joints\n",
        "- **Structures**: Multiple modes can be excited by earthquakes\n",
        "- **Chaos**: Can be useful (mixing) or problematic (prediction)\n",
        "\n",
        "### Connection to Vibrations (Unit 5.2)\n",
        "\n",
        "This lecture sets the stage:\n",
        "- **SDOF vibrations**: One mass-spring (next lecture)\n",
        "- **MDOF vibrations**: Multiple masses (modal analysis)\n",
        "- **Damping**: Add $\\mathbf{C}\\dot{\\mathbf{q}}$ terms\n",
        "- **Forced response**: Add $\\mathbf{F}(t)$ forcing\n",
        "\n",
        "### What's Next?\n",
        "\n",
        "**Unit 5 Lecture 4**: Introduction to Vibrations\n",
        "- Single DOF vibrations (SDOF)\n",
        "- Natural frequency $\\omega_n = \\sqrt{k/m}$\n",
        "- Damping ratio $\\zeta$\n",
        "- Free and forced response\n",
        "- Resonance\n",
        "\n",
        "---\n",
        "\n",
        "### Practice Problems\n",
        "\n",
        "1. **Three masses**: Add third mass to spring system, find 3 natural frequencies\n",
        "2. **Double pendulum**: Small angles → linearize equations, find normal modes\n",
        "3. **Triple pendulum**: Even more chaotic! Try simulating\n",
        "4. **Robot arm**: Two links with motors, derive equations with torque inputs\n",
        "\n",
        "---\n"
    ]
})

# Save notebook
os.makedirs(output_dir, exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("=" * 60)
print("Unit 5 Lecture 3 Created Successfully!")
print("=" * 60)
print(f"\nFile: {output_path}")
print(f"\nNotebook structure:")
print(f"Total cells: {len(notebook['cells'])}")
print(f"Markdown: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'markdown')}")
print(f"Code: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'code')}")
print(f"\nContent:")
print(f"Part A: Two-Mass-Spring System (normal modes)")
print(f"Part B: Double Pendulum (nonlinear, chaotic)")
print(f"Example 3: Chaos demonstration (butterfly effect)")
print(f"\nDuration: ~90 minutes")
print(f"\nReady to test!")
