"""
Create Unit 5 Lecture 2: Coupled Translation-Rotation Systems
Focus: Multi-body mechanisms, linkages, kinematic constraints
Target: ~90 minutes comprehensive coverage
"""

import json
import os
import numpy as np

# Paths
output_dir = r"d:\Sunny\DSM\notebooks\Teacher"
output_path = os.path.join(output_dir, "T_U5_L2_Coupled_Systems_and_Mechanisms.ipynb")

# Create notebook structure
notebook = {
    "cells": [],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.14.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

# Cell 1: Header
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# ⚙️ Unit 5 Lecture 2: Coupled Translation-Rotation Systems\n",
        "## Multi-Body Mechanisms & Kinematic Constraints\n",
        "\n",
        "---\n",
        "\n",
        "### 🎯 Learning Objectives\n",
        "By the end of this lecture, you will be able to:\n",
        "1. **Analyze coupled systems** where translation and rotation are linked\n",
        "2. **Apply rolling constraints** (v = ωR) to find accelerations\n",
        "3. **Model mechanisms** (yo-yo, slider-crank, four-bar linkage)\n",
        "4. **Derive kinematic relationships** between connected rigid bodies\n",
        "5. **Solve multi-body problems** using constraint equations\n",
        "\n",
        "### 📚 Context\n",
        "**From single body to multi-body:**\n",
        "- Lecture 1: Single rigid body → translation + rotation independently\n",
        "- **This lecture**: Multiple bodies → motion coupled by constraints\n",
        "\n",
        "**Real-world applications**:\n",
        "- Yo-yo: rotation → unwinding → translation\n",
        "- Engine: slider-crank converts rotation ↔ translation\n",
        "- Robot arm: joints couple multiple links\n",
        "- Transmission: gears transfer motion with ratio\n",
        "\n",
        "### 🔑 Key Concepts\n",
        "**Constraint equations**: Relate motions of different bodies\n",
        "- Rolling: $v_{cm} = \\omega R$\n",
        "- Linkage: geometry determines velocity ratios\n",
        "- Gears: $\\omega_1 r_1 = \\omega_2 r_2$ (no slip)\n",
        "\n",
        "**Strategy**: Write equations for each body + constraint → solve system\n",
        "\n",
        "---\n"
    ]
})

# Cell 2: Imports
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Import libraries\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from matplotlib.animation import FuncAnimation\n",
        "from matplotlib.patches import Circle, Rectangle, FancyArrowPatch\n",
        "from scipy.integrate import odeint\n",
        "from IPython.display import HTML\n",
        "\n",
        "# Plotting style\n",
        "plt.style.use('seaborn-v0_8-darkgrid')\n",
        "plt.rcParams['figure.figsize'] = (12, 4)\n",
        "\n",
        "print(\"✓ Libraries imported successfully!\")\n",
        "print(\"  Ready for coupled systems analysis...\")\n"
    ]
})

# Cell 3: Yo-yo Theory
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part A: The Yo-Yo Problem 🪀\n",
        "\n",
        "### Setup\n",
        "**System**: Disk (mass m, radius R, moment of inertia I) with string wound around inner radius r\n",
        "\n",
        "**Key insight**: Rotation causes unwinding → translation!\n",
        "\n",
        "### Free Body Diagram\n",
        "Forces on yo-yo:\n",
        "- Weight: $mg$ (down)\n",
        "- Tension: $T$ (up, acting at radius r)\n",
        "\n",
        "### Equations of Motion\n",
        "\n",
        "**Translation** (taking down as positive):\n",
        "$$m a = mg - T$$\n",
        "\n",
        "**Rotation** (about center of mass):\n",
        "$$I \\alpha = T r$$\n",
        "\n",
        "where torque from tension causes rotation.\n",
        "\n",
        "**Constraint** (string unwinds without slip):\n",
        "$$a = \\alpha r$$\n",
        "\n",
        "This relates linear acceleration (down) to angular acceleration (rotation).\n",
        "\n",
        "### Solution\n",
        "\n",
        "From constraint: $\\alpha = a/r$\n",
        "\n",
        "From rotation equation: $T = I\\alpha/r = Ia/r^2$\n",
        "\n",
        "Substitute into translation:\n",
        "$$m a = mg - \\frac{Ia}{r^2}$$\n",
        "\n",
        "$$a \\left(m + \\frac{I}{r^2}\\right) = mg$$\n",
        "\n",
        "$$\\boxed{a = \\frac{mg}{m + I/r^2} = \\frac{g}{1 + I/(mr^2)}}$$\n",
        "\n",
        "**Tension**:\n",
        "$$\\boxed{T = \\frac{mgI/(mr^2)}{1 + I/(mr^2)}}$$\n",
        "\n",
        "### Special Cases\n",
        "\n",
        "**1. Thin disk** ($I = \\frac{1}{2}mR^2$, $r = R$):\n",
        "$$a = \\frac{g}{1 + 1/2} = \\frac{2g}{3} \\approx 6.54 \\text{ m/s}^2$$\n",
        "\n",
        "**2. Point mass** ($I = 0$, or $r = 0$):\n",
        "$$a = g \\quad \\text{(free fall!)}$$\n",
        "\n",
        "**3. Very large I or small r**:\n",
        "$$a \\to 0 \\quad \\text{(heavy flywheel resists unwinding)}$$\n",
        "\n",
        "### Physical Insight\n",
        "- Yo-yo falls **slower than free fall** ($a < g$) because rotational inertia resists\n",
        "- Smaller inner radius r → slower fall (more mechanical advantage)\n",
        "- String tension does **negative work** on translation but **positive work** on rotation\n",
        "\n",
        "---\n"
    ]
})

# Cell 4: Yo-yo Simulation
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 1: Yo-Yo Dynamics\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 1: Yo-Yo Falling and Unwinding\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "m = 0.05  # kg (50 grams)\n",
        "R = 0.03  # m (30 mm outer radius)\n",
        "r = 0.01  # m (10 mm inner radius where string wraps)\n",
        "I = 0.5 * m * R**2  # Solid disk\n",
        "g = 9.81  # m/s^2\n",
        "\n",
        "# Calculate acceleration and tension\n",
        "beta = I / (m * r**2)  # Dimensionless parameter\n",
        "a = g / (1 + beta)\n",
        "T = (beta / (1 + beta)) * m * g\n",
        "\n",
        "# Angular acceleration\n",
        "alpha = a / r\n",
        "\n",
        "print(f\"\\nYo-Yo Properties:\")\n",
        "print(f\"  Mass: {m*1000:.1f} g\")\n",
        "print(f\"  Outer radius R: {R*1000:.1f} mm\")\n",
        "print(f\"  Inner radius r: {r*1000:.1f} mm\")\n",
        "print(f\"  Moment of inertia: {I*1e6:.4f} kg·mm²\")\n",
        "print(f\"  β = I/(mr²): {beta:.4f}\")\n",
        "\n",
        "print(f\"\\nDynamics:\")\n",
        "print(f\"  Acceleration (down): {a:.3f} m/s² ({a/g*100:.1f}% of g)\")\n",
        "print(f\"  Free fall would be: {g:.3f} m/s²\")\n",
        "print(f\"  Angular acceleration: {alpha:.2f} rad/s²\")\n",
        "print(f\"  String tension: {T*1000:.3f} mN\")\n",
        "print(f\"  Weight: {m*g*1000:.3f} mN\")\n",
        "\n",
        "# Simulate descent\n",
        "t_fall = 1.0  # seconds\n",
        "t = np.linspace(0, t_fall, 500)\n",
        "\n",
        "# Kinematics\n",
        "y = 0.5 * a * t**2  # Descend distance\n",
        "v = a * t  # Velocity\n",
        "omega = alpha * t  # Angular velocity\n",
        "theta = 0.5 * alpha * t**2  # Angle rotated\n",
        "\n",
        "# Energy analysis\n",
        "KE_trans = 0.5 * m * v**2\n",
        "KE_rot = 0.5 * I * omega**2\n",
        "KE_total = KE_trans + KE_rot\n",
        "PE_lost = m * g * y\n",
        "\n",
        "# Plotting\n",
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
        "\n",
        "# Position and rotation\n",
        "ax1 = axes[0, 0]\n",
        "ax1_twin = ax1.twinx()\n",
        "line1 = ax1.plot(t, y*100, 'b-', linewidth=2.5, label='Distance fallen')\n",
        "line2 = ax1_twin.plot(t, theta, 'r-', linewidth=2.5, label='Angle rotated')\n",
        "ax1.set_xlabel('Time (s)', fontsize=11)\n",
        "ax1.set_ylabel('Distance (cm)', fontsize=11, color='b')\n",
        "ax1_twin.set_ylabel('Angle (rad)', fontsize=11, color='r')\n",
        "ax1.tick_params(axis='y', labelcolor='b')\n",
        "ax1_twin.tick_params(axis='y', labelcolor='r')\n",
        "ax1.set_title('Position: Falling + Rotating', fontsize=12, fontweight='bold')\n",
        "lines = line1 + line2\n",
        "labels = [l.get_label() for l in lines]\n",
        "ax1.legend(lines, labels, loc='upper left', fontsize=10)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Velocities\n",
        "ax2 = axes[0, 1]\n",
        "ax2_twin = ax2.twinx()\n",
        "line3 = ax2.plot(t, v*100, 'b-', linewidth=2.5, label='Linear velocity')\n",
        "line4 = ax2_twin.plot(t, omega, 'r-', linewidth=2.5, label='Angular velocity')\n",
        "ax2.set_xlabel('Time (s)', fontsize=11)\n",
        "ax2.set_ylabel('Velocity (cm/s)', fontsize=11, color='b')\n",
        "ax2_twin.set_ylabel('Angular velocity (rad/s)', fontsize=11, color='r')\n",
        "ax2.tick_params(axis='y', labelcolor='b')\n",
        "ax2_twin.tick_params(axis='y', labelcolor='r')\n",
        "ax2.set_title('Velocities: v = αr (Constraint)', fontsize=12, fontweight='bold')\n",
        "lines = line3 + line4\n",
        "labels = [l.get_label() for l in lines]\n",
        "ax2.legend(lines, labels, loc='upper left', fontsize=10)\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "# Check constraint\n",
        "v_check = omega * r\n",
        "ax2.plot(t, v_check*100, 'g--', linewidth=2, alpha=0.7, label='ωr (should match v)')\n",
        "\n",
        "# Energy distribution\n",
        "ax3 = axes[1, 0]\n",
        "ax3.plot(t, KE_trans*1000, 'b-', linewidth=2, label='KE translational')\n",
        "ax3.plot(t, KE_rot*1000, 'r-', linewidth=2, label='KE rotational')\n",
        "ax3.plot(t, KE_total*1000, 'purple', linewidth=2.5, label='KE total')\n",
        "ax3.plot(t, PE_lost*1000, 'g--', linewidth=2, label='PE lost (mgy)')\n",
        "ax3.set_xlabel('Time (s)', fontsize=11)\n",
        "ax3.set_ylabel('Energy (mJ)', fontsize=11)\n",
        "ax3.set_title('Energy Conservation', fontsize=12, fontweight='bold')\n",
        "ax3.legend(fontsize=9)\n",
        "ax3.grid(True, alpha=0.3)\n",
        "\n",
        "# Energy fractions\n",
        "ax4 = axes[1, 1]\n",
        "frac_trans = KE_trans / (KE_total + 1e-12)\n",
        "frac_rot = KE_rot / (KE_total + 1e-12)\n",
        "ax4.plot(t[1:], frac_trans[1:]*100, 'b-', linewidth=2.5, label='Translational %')\n",
        "ax4.plot(t[1:], frac_rot[1:]*100, 'r-', linewidth=2.5, label='Rotational %')\n",
        "ax4.axhline(y=50, color='k', linestyle='--', alpha=0.3)\n",
        "ax4.set_xlabel('Time (s)', fontsize=11)\n",
        "ax4.set_ylabel('Energy Fraction (%)', fontsize=11)\n",
        "ax4.set_title('Energy Distribution', fontsize=12, fontweight='bold')\n",
        "ax4.legend(fontsize=10)\n",
        "ax4.grid(True, alpha=0.3)\n",
        "ax4.set_ylim([0, 100])\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Final values\n",
        "print(f\"\\n📊 After {t_fall} second:\")\n",
        "print(f\"  Distance fallen: {y[-1]*100:.2f} cm\")\n",
        "print(f\"  Revolutions: {theta[-1]/(2*np.pi):.2f}\")\n",
        "print(f\"  Final velocity: {v[-1]*100:.2f} cm/s\")\n",
        "print(f\"  Final ω: {omega[-1]:.2f} rad/s = {omega[-1]/(2*np.pi):.2f} rev/s\")\n",
        "print(f\"\\n✓ Constraint check: v = {v[-1]*100:.4f} cm/s, ωr = {v_check[-1]*100:.4f} cm/s\")\n",
        "print(f\"✓ Energy check: KE = {KE_total[-1]*1000:.4f} mJ, PE = {PE_lost[-1]*1000:.4f} mJ\")\n",
        "print(f\"\\n💡 Energy split: {frac_trans[-1]*100:.1f}% translational, {frac_rot[-1]*100:.1f}% rotational\")\n"
    ]
})

# Cell 5: Slider-Crank Theory
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part B: Slider-Crank Mechanism ⚙️\n",
        "\n",
        "### What is a Slider-Crank?\n",
        "**Definition**: Converts rotary motion ↔ linear motion\n",
        "- **Examples**: Engine piston, reciprocating saw, hydraulic press\n",
        "- **Components**: Crank (rotates), connecting rod (links), slider (translates)\n",
        "\n",
        "### Geometry\n",
        "\n",
        "**Setup**: \n",
        "- Crank: radius $r$, angle $\\theta$ (from horizontal)\n",
        "- Connecting rod: length $L$\n",
        "- Slider: horizontal position $x$\n",
        "\n",
        "**Position relationship**:\n",
        "$$x = r\\cos\\theta + L\\cos\\phi$$\n",
        "\n",
        "where $\\phi$ = angle of connecting rod, found from:\n",
        "$$r\\sin\\theta = L\\sin\\phi$$\n",
        "$$\\sin\\phi = \\frac{r}{L}\\sin\\theta$$\n",
        "\n",
        "### Velocity Analysis\n",
        "\n",
        "**Given**: Crank rotates with angular velocity $\\omega$ (constant)\n",
        "\n",
        "**Find**: Slider velocity $v_x = \\dot{x}$\n",
        "\n",
        "Differentiate position:\n",
        "$$v_x = -r\\omega\\sin\\theta - L\\dot{\\phi}\\sin\\phi$$\n",
        "\n",
        "From constraint:\n",
        "$$r\\omega\\cos\\theta = L\\dot{\\phi}\\cos\\phi$$\n",
        "$$\\dot{\\phi} = \\frac{r\\omega\\cos\\theta}{L\\cos\\phi}$$\n",
        "\n",
        "Substitute:\n",
        "$$v_x = -r\\omega\\sin\\theta - r\\omega\\cos\\theta\\tan\\phi$$\n",
        "$$\\boxed{v_x = -r\\omega\\left(\\sin\\theta + \\frac{r}{L}\\frac{\\sin\\theta\\cos\\theta}{\\cos\\phi}\\right)}$$\n",
        "\n",
        "### Simplified Form (Long Rod Approximation)\n",
        "If $L \\gg r$, then $\\phi \\approx 0$ and:\n",
        "$$v_x \\approx -r\\omega\\sin\\theta$$\n",
        "\n",
        "**Maximum velocity**: When $\\theta = 90°$ (crank vertical)\n",
        "$$|v_x|_{\\max} \\approx r\\omega$$\n",
        "\n",
        "### Acceleration\n",
        "Differentiate velocity → complex! Key features:\n",
        "- Maximum at dead centers ($\\theta = 0°, 180°$)\n",
        "- Asymmetric: faster on one stroke than the other\n",
        "- Creates vibrations in real engines\n",
        "\n",
        "---\n"
    ]
})

# Cell 6: Slider-Crank Simulation
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 2: Slider-Crank Kinematics\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 2: Slider-Crank Mechanism (Engine)\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "r = 0.05  # m (crank radius, 50mm stroke → 100mm total)\n",
        "L = 0.15  # m (connecting rod length)\n",
        "omega = 20.0  # rad/s (constant angular velocity)\n",
        "\n",
        "print(f\"\\nMechanism Properties:\")\n",
        "print(f\"  Crank radius: {r*1000:.1f} mm\")\n",
        "print(f\"  Connecting rod length: {L*1000:.1f} mm\")\n",
        "print(f\"  Ratio L/r: {L/r:.2f}\")\n",
        "print(f\"  Crank speed: {omega:.1f} rad/s = {omega/(2*np.pi)*60:.1f} RPM\")\n",
        "\n",
        "# Simulate one complete revolution\n",
        "theta = np.linspace(0, 2*np.pi, 500)\n",
        "\n",
        "# Position analysis\n",
        "sin_phi = (r/L) * np.sin(theta)\n",
        "phi = np.arcsin(sin_phi)\n",
        "cos_phi = np.cos(phi)\n",
        "\n",
        "x = r * np.cos(theta) + L * cos_phi\n",
        "\n",
        "# Velocity analysis\n",
        "phi_dot = (r * omega * np.cos(theta)) / (L * cos_phi)\n",
        "v_x = -r * omega * np.sin(theta) - L * phi_dot * np.sin(phi)\n",
        "\n",
        "# Acceleration (numerical differentiation)\n",
        "a_x = np.gradient(v_x, theta) * omega\n",
        "\n",
        "# Crank and connecting rod positions for visualization\n",
        "crank_x = r * np.cos(theta)\n",
        "crank_y = r * np.sin(theta)\n",
        "rod_end_x = x\n",
        "rod_end_y = np.zeros_like(x)\n",
        "\n",
        "# Maximum values\n",
        "x_min, x_max = x.min(), x.max()\n",
        "v_x_max = np.abs(v_x).max()\n",
        "a_x_max = np.abs(a_x).max()\n",
        "\n",
        "print(f\"\\nKinematics:\")\n",
        "print(f\"  Stroke (x range): {(x_max - x_min)*1000:.2f} mm\")\n",
        "print(f\"  Theoretical stroke: {2*r*1000:.2f} mm\")\n",
        "print(f\"  Max slider velocity: {v_x_max*1000:.2f} mm/s\")\n",
        "print(f\"  Theoretical v_max: {r*omega*1000:.2f} mm/s (rω)\")\n",
        "print(f\"  Max slider acceleration: {a_x_max:.2f} m/s²\")\n",
        "\n",
        "# Plotting\n",
        "fig = plt.figure(figsize=(16, 10))\n",
        "\n",
        "# Mechanism diagram (4 positions)\n",
        "ax1 = plt.subplot(2, 3, 1)\n",
        "positions = [0, np.pi/2, np.pi, 3*np.pi/2]  # 0°, 90°, 180°, 270°\n",
        "colors = ['red', 'blue', 'green', 'purple']\n",
        "labels = ['0° (TDC)', '90°', '180° (BDC)', '270°']\n",
        "\n",
        "for pos, color, label in zip(positions, colors, labels):\n",
        "    idx = np.argmin(np.abs(theta - pos))\n",
        "    cx, cy = crank_x[idx], crank_y[idx]\n",
        "    rx = x[idx]\n",
        "    \n",
        "    # Crank\n",
        "    ax1.plot([0, cx], [0, cy], 'o-', color=color, linewidth=3, markersize=8)\n",
        "    # Connecting rod\n",
        "    ax1.plot([cx, rx], [cy, 0], 's-', color=color, linewidth=2, markersize=6, alpha=0.7)\n",
        "    # Slider\n",
        "    ax1.plot(rx, 0, 'D', color=color, markersize=10, label=label)\n",
        "\n",
        "ax1.plot(0, 0, 'ko', markersize=12, label='Pivot')\n",
        "ax1.axhline(y=0, color='k', linestyle='--', alpha=0.3)\n",
        "ax1.set_xlim([-0.05, 0.25])\n",
        "ax1.set_ylim([-0.08, 0.08])\n",
        "ax1.set_aspect('equal')\n",
        "ax1.set_xlabel('x (m)', fontsize=10)\n",
        "ax1.set_ylabel('y (m)', fontsize=10)\n",
        "ax1.set_title('Mechanism at 4 Positions', fontsize=11, fontweight='bold')\n",
        "ax1.legend(fontsize=8, loc='upper right')\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Slider position vs crank angle\n",
        "ax2 = plt.subplot(2, 3, 2)\n",
        "ax2.plot(np.degrees(theta), x*1000, 'b-', linewidth=2)\n",
        "ax2.axhline(y=x_min*1000, color='r', linestyle='--', alpha=0.5, label='BDC')\n",
        "ax2.axhline(y=x_max*1000, color='g', linestyle='--', alpha=0.5, label='TDC')\n",
        "ax2.set_xlabel('Crank Angle (degrees)', fontsize=10)\n",
        "ax2.set_ylabel('Slider Position (mm)', fontsize=10)\n",
        "ax2.set_title('Position vs Angle', fontsize=11, fontweight='bold')\n",
        "ax2.legend(fontsize=9)\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "# Slider velocity vs crank angle\n",
        "ax3 = plt.subplot(2, 3, 3)\n",
        "ax3.plot(np.degrees(theta), v_x*1000, 'g-', linewidth=2)\n",
        "ax3.axhline(y=0, color='k', linestyle='-', alpha=0.3)\n",
        "ax3.set_xlabel('Crank Angle (degrees)', fontsize=10)\n",
        "ax3.set_ylabel('Slider Velocity (mm/s)', fontsize=10)\n",
        "ax3.set_title('Velocity vs Angle', fontsize=11, fontweight='bold')\n",
        "ax3.grid(True, alpha=0.3)\n",
        "\n",
        "# Slider acceleration vs crank angle\n",
        "ax4 = plt.subplot(2, 3, 4)\n",
        "ax4.plot(np.degrees(theta), a_x, 'r-', linewidth=2)\n",
        "ax4.axhline(y=0, color='k', linestyle='-', alpha=0.3)\n",
        "ax4.set_xlabel('Crank Angle (degrees)', fontsize=10)\n",
        "ax4.set_ylabel('Slider Acceleration (m/s²)', fontsize=10)\n",
        "ax4.set_title('Acceleration vs Angle (Note Asymmetry!)', fontsize=11, fontweight='bold')\n",
        "ax4.grid(True, alpha=0.3)\n",
        "\n",
        "# Phase plot: velocity vs position\n",
        "ax5 = plt.subplot(2, 3, 5)\n",
        "ax5.plot(x*1000, v_x*1000, 'purple', linewidth=2)\n",
        "ax5.set_xlabel('Position (mm)', fontsize=10)\n",
        "ax5.set_ylabel('Velocity (mm/s)', fontsize=10)\n",
        "ax5.set_title('Phase Portrait', fontsize=11, fontweight='bold')\n",
        "ax5.grid(True, alpha=0.3)\n",
        "\n",
        "# Connecting rod angle\n",
        "ax6 = plt.subplot(2, 3, 6)\n",
        "ax6.plot(np.degrees(theta), np.degrees(phi), 'orange', linewidth=2)\n",
        "ax6.set_xlabel('Crank Angle (degrees)', fontsize=10)\n",
        "ax6.set_ylabel('Connecting Rod Angle φ (degrees)', fontsize=10)\n",
        "ax6.set_title('Rod Angle vs Crank Angle', fontsize=11, fontweight='bold')\n",
        "ax6.grid(True, alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n💡 Key observations:\")\n",
        "print(\"  1. Position: sinusoidal-like, but not perfect sine (due to rod length)\")\n",
        "print(\"  2. Velocity: NOT symmetric! Faster on one side\")\n",
        "print(\"  3. Acceleration: Peaks at dead centers (TDC, BDC)\")\n",
        "print(\"  4. Rod angle: oscillates ±arcsin(r/L) from vertical\")\n"
    ]
})

# Cell 7: Gears Theory
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## Part C: Gear Trains ⚙️⚙️\n",
        "\n",
        "### Basics\n",
        "**Purpose**: Transfer rotation with speed/torque ratio\n",
        "\n",
        "**No-slip condition** (teeth mesh):\n",
        "$$r_1 \\omega_1 = r_2 \\omega_2$$\n",
        "\n",
        "**Gear ratio**:\n",
        "$$GR = \\frac{\\omega_2}{\\omega_1} = \\frac{r_1}{r_2} = \\frac{N_1}{N_2}$$\n",
        "\n",
        "where $N$ = number of teeth\n",
        "\n",
        "### Torque Relationship\n",
        "\n",
        "**Assuming ideal (no losses)**:\n",
        "$$P_1 = P_2 \\quad \\text{(power conservation)}$$\n",
        "$$\\tau_1 \\omega_1 = \\tau_2 \\omega_2$$\n",
        "$$\\frac{\\tau_2}{\\tau_1} = \\frac{\\omega_1}{\\omega_2} = \\frac{r_2}{r_1}$$\n",
        "\n",
        "**Key insight**: \n",
        "- Speed down → torque up (reduction)\n",
        "- Speed up → torque down (overdrive)\n",
        "\n",
        "### Compound Gear Train\n",
        "**Multiple stages**: Gears 1→2→3→4\n",
        "\n",
        "**Overall ratio**:\n",
        "$$GR_{total} = \\frac{\\omega_{out}}{\\omega_{in}} = \\prod_i \\frac{r_{drive,i}}{r_{driven,i}}$$\n",
        "\n",
        "**Example**: Three-stage reduction\n",
        "- Stage 1: 10T → 50T (ratio 1:5)\n",
        "- Stage 2: 10T → 50T (ratio 1:5)\n",
        "- Stage 3: 10T → 50T (ratio 1:5)\n",
        "- **Total**: 1:125 reduction!\n",
        "\n",
        "### Applications\n",
        "- **Car transmission**: Change torque/speed for different driving conditions\n",
        "- **Robot joints**: High-torque motors are heavy → use motors + gearbox\n",
        "- **Clock**: Precise gear ratios for hour/minute/second hands\n",
        "\n",
        "---\n"
    ]
})

# Cell 8: Gear Train Simulation
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Example 3: Two-Stage Gear Train\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"Example 3: Two-Stage Gear Reduction\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Given\n",
        "# Stage 1: Input shaft (gear 1) drives gear 2\n",
        "N1 = 15  # teeth on input gear\n",
        "N2 = 45  # teeth on first driven gear\n",
        "\n",
        "# Stage 2: Gear 3 (on same shaft as gear 2) drives gear 4\n",
        "N3 = 12  # teeth on second driving gear\n",
        "N4 = 60  # teeth on output gear\n",
        "\n",
        "# Motor specs\n",
        "omega_motor = 100.0  # rad/s (motor speed)\n",
        "tau_motor = 0.5  # N·m (motor torque)\n",
        "P_motor = tau_motor * omega_motor  # Power\n",
        "\n",
        "# Gear ratios\n",
        "GR1 = N1 / N2  # Stage 1\n",
        "GR2 = N3 / N4  # Stage 2\n",
        "GR_total = GR1 * GR2  # Overall\n",
        "\n",
        "# Output shaft\n",
        "omega_output = omega_motor * GR_total\n",
        "tau_output = tau_motor / GR_total  # Assuming 100% efficiency\n",
        "P_output = tau_output * omega_output\n",
        "\n",
        "# Intermediate shaft (between stages)\n",
        "omega_intermediate = omega_motor * GR1\n",
        "\n",
        "print(f\"\\nGear Specifications:\")\n",
        "print(f\"  Stage 1: {N1}T → {N2}T (ratio {GR1:.4f} or 1:{1/GR1:.1f})\")\n",
        "print(f\"  Stage 2: {N3}T → {N4}T (ratio {GR2:.4f} or 1:{1/GR2:.1f})\")\n",
        "print(f\"  Overall: 1:{1/GR_total:.1f} reduction\")\n",
        "\n",
        "print(f\"\\nMotor (Input):\")\n",
        "print(f\"  Speed: {omega_motor:.2f} rad/s = {omega_motor/(2*np.pi)*60:.1f} RPM\")\n",
        "print(f\"  Torque: {tau_motor:.3f} N·m\")\n",
        "print(f\"  Power: {P_motor:.3f} W\")\n",
        "\n",
        "print(f\"\\nIntermediate Shaft:\")\n",
        "print(f\"  Speed: {omega_intermediate:.2f} rad/s = {omega_intermediate/(2*np.pi)*60:.1f} RPM\")\n",
        "\n",
        "print(f\"\\nOutput Shaft:\")\n",
        "print(f\"  Speed: {omega_output:.2f} rad/s = {omega_output/(2*np.pi)*60:.1f} RPM\")\n",
        "print(f\"  Torque: {tau_output:.3f} N·m (×{tau_output/tau_motor:.1f} amplification!)\")\n",
        "print(f\"  Power: {P_output:.3f} W (conservation ✓)\")\n",
        "\n",
        "# Simulate rotation over time\n",
        "t = np.linspace(0, 2, 500)  # 2 seconds\n",
        "\n",
        "theta_motor = omega_motor * t\n",
        "theta_intermediate = omega_intermediate * t\n",
        "theta_output = omega_output * t\n",
        "\n",
        "# Plotting\n",
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
        "\n",
        "# Angular positions\n",
        "ax1 = axes[0, 0]\n",
        "ax1.plot(t, theta_motor, 'r-', linewidth=2.5, label='Motor (input)')\n",
        "ax1.plot(t, theta_intermediate, 'b-', linewidth=2.5, label='Intermediate')\n",
        "ax1.plot(t, theta_output, 'g-', linewidth=2.5, label='Output')\n",
        "ax1.set_xlabel('Time (s)', fontsize=11)\n",
        "ax1.set_ylabel('Angle (rad)', fontsize=11)\n",
        "ax1.set_title('Angular Position vs Time', fontsize=12, fontweight='bold')\n",
        "ax1.legend(fontsize=10)\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Speed comparison (bar chart)\n",
        "ax2 = axes[0, 1]\n",
        "shafts = ['Motor\\n(Input)', 'Intermediate', 'Output']\n",
        "speeds = [omega_motor, omega_intermediate, omega_output]\n",
        "rpm = [s/(2*np.pi)*60 for s in speeds]\n",
        "colors_bar = ['red', 'blue', 'green']\n",
        "bars = ax2.bar(shafts, rpm, color=colors_bar, alpha=0.7, edgecolor='black', linewidth=2)\n",
        "ax2.set_ylabel('Speed (RPM)', fontsize=11)\n",
        "ax2.set_title('Speed at Each Shaft', fontsize=12, fontweight='bold')\n",
        "ax2.grid(axis='y', alpha=0.3)\n",
        "for bar, val in zip(bars, rpm):\n",
        "    height = bar.get_height()\n",
        "    ax2.text(bar.get_x() + bar.get_width()/2, height + 5,\n",
        "             f'{val:.1f}', ha='center', va='bottom', fontsize=10, fontweight='bold')\n",
        "\n",
        "# Torque comparison (bar chart)\n",
        "ax3 = axes[1, 0]\n",
        "torques = [tau_motor, tau_motor/GR1, tau_output]\n",
        "bars = ax3.bar(shafts, torques, color=colors_bar, alpha=0.7, edgecolor='black', linewidth=2)\n",
        "ax3.set_ylabel('Torque (N·m)', fontsize=11)\n",
        "ax3.set_title('Torque at Each Shaft', fontsize=12, fontweight='bold')\n",
        "ax3.grid(axis='y', alpha=0.3)\n",
        "for bar, val in zip(bars, torques):\n",
        "    height = bar.get_height()\n",
        "    ax3.text(bar.get_x() + bar.get_width()/2, height + 0.3,\n",
        "             f'{val:.2f}', ha='center', va='bottom', fontsize=10, fontweight='bold')\n",
        "\n",
        "# Gear diagram (schematic)\n",
        "ax4 = axes[1, 1]\n",
        "# Draw circles representing gears (radii proportional to teeth)\n",
        "r1 = N1 / 10\n",
        "r2 = N2 / 10\n",
        "r3 = N3 / 10\n",
        "r4 = N4 / 10\n",
        "\n",
        "# Positions\n",
        "gear1_center = (0, 0)\n",
        "gear2_center = (0, r1 + r2)\n",
        "gear3_center = (r2 + r3 + 0.5, r1 + r2)\n",
        "gear4_center = (r2 + r3 + 0.5, r1 + r2 + r3 + r4)\n",
        "\n",
        "# Draw gears\n",
        "gear1 = Circle(gear1_center, r1, color='red', alpha=0.6, ec='black', linewidth=2)\n",
        "gear2 = Circle(gear2_center, r2, color='blue', alpha=0.6, ec='black', linewidth=2)\n",
        "gear3 = Circle(gear3_center, r3, color='blue', alpha=0.6, ec='black', linewidth=2)\n",
        "gear4 = Circle(gear4_center, r4, color='green', alpha=0.6, ec='black', linewidth=2)\n",
        "\n",
        "ax4.add_patch(gear1)\n",
        "ax4.add_patch(gear2)\n",
        "ax4.add_patch(gear3)\n",
        "ax4.add_patch(gear4)\n",
        "\n",
        "# Labels\n",
        "ax4.text(gear1_center[0], gear1_center[1], f'{N1}T', ha='center', va='center', fontsize=12, fontweight='bold')\n",
        "ax4.text(gear2_center[0], gear2_center[1], f'{N2}T', ha='center', va='center', fontsize=12, fontweight='bold')\n",
        "ax4.text(gear3_center[0], gear3_center[1], f'{N3}T', ha='center', va='center', fontsize=12, fontweight='bold')\n",
        "ax4.text(gear4_center[0], gear4_center[1], f'{N4}T', ha='center', va='center', fontsize=12, fontweight='bold')\n",
        "\n",
        "# Arrows for rotation direction\n",
        "ax4.annotate('', xy=(0.5, -0.5), xytext=(-0.5, -0.5),\n",
        "             arrowprops=dict(arrowstyle='->', lw=2, color='red'))\n",
        "ax4.text(-1, -1, 'Motor\\nInput', ha='center', fontsize=10, fontweight='bold', color='red')\n",
        "ax4.text(gear4_center[0], gear4_center[1] + r4 + 1, 'Output', ha='center', fontsize=10, fontweight='bold', color='green')\n",
        "\n",
        "ax4.set_xlim([-3, 10])\n",
        "ax4.set_ylim([-3, 15])\n",
        "ax4.set_aspect('equal')\n",
        "ax4.axis('off')\n",
        "ax4.set_title('Gear Train Schematic', fontsize=12, fontweight='bold')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n💡 Trade-off: Speed ↓ → Torque ↑ (Power conserved)\")\n",
        "print(f\"   This reduction gives {tau_output/tau_motor:.1f}× more torque at output!\")\n"
    ]
})

# Cell 9: Summary
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## 📝 Summary\n",
        "\n",
        "### Key Concepts\n",
        "\n",
        "**1. Coupled Systems**\n",
        "- Translation + rotation linked by constraints\n",
        "- Write equations for each motion type + constraint equation\n",
        "- Solve system to find accelerations\n",
        "\n",
        "**2. Yo-Yo**\n",
        "$$a = \\frac{g}{1 + I/(mr^2)} < g \\quad \\text{(slower than free fall)}$$\n",
        "- Rotational inertia resists unwinding\n",
        "- Smaller inner radius → slower descent\n",
        "\n",
        "**3. Slider-Crank**\n",
        "- Converts rotation ↔ translation (engine, pump)\n",
        "- Kinematics: $x = r\\cos\\theta + L\\cos\\phi$\n",
        "- Velocity: NOT sinusoidal (asymmetric due to rod angle)\n",
        "- Acceleration: peaks at dead centers\n",
        "\n",
        "**4. Gear Trains**\n",
        "$$\\frac{\\omega_2}{\\omega_1} = \\frac{r_1}{r_2} = \\frac{N_1}{N_2} \\quad \\text{(speed ratio)}$$\n",
        "$$\\frac{\\tau_2}{\\tau_1} = \\frac{r_2}{r_1} \\quad \\text{(torque ratio)}$$\n",
        "- Power conserved: $\\tau_1 \\omega_1 = \\tau_2 \\omega_2$\n",
        "- Compound gears: multiply ratios\n",
        "\n",
        "### Problem-Solving Strategy\n",
        "\n",
        "**For coupled systems**:\n",
        "1. **Identify bodies**: How many rigid bodies?\n",
        "2. **FBD each body**: All forces, where they act\n",
        "3. **Equations per body**:\n",
        "   - Translation: ΣF = ma\n",
        "   - Rotation: Στ = Iα\n",
        "4. **Constraint equations**: How are motions related?\n",
        "   - Rolling: v = ωR\n",
        "   - Linkage: geometric relationships\n",
        "   - Gears: no-slip condition\n",
        "5. **Solve system**: Eliminate unknowns, find desired quantities\n",
        "\n",
        "### Design Insights\n",
        "\n",
        "- **Yo-yo**: Want slow descent → large I, small r\n",
        "- **Engine**: Long connecting rod L → smoother motion, less vibration\n",
        "- **Gearbox**: High reduction → high torque, but slower\n",
        "- **Robot**: Multiple stages → compact, high torque-to-weight\n",
        "\n",
        "### What's Next?\n",
        "\n",
        "**Unit 5 Lecture 3**: 1-2 DOF Rigid Body Systems\n",
        "- Coupled pendulums\n",
        "- Double pendulum\n",
        "- Matrix formulation M·q̈ + C·q̇ + K·q = F\n",
        "- Introduction to normal modes\n",
        "\n",
        "---\n",
        "\n",
        "### 🧪 Practice Problems\n",
        "\n",
        "1. **Modified yo-yo**: Inner radius r = R/2, what's the acceleration?\n",
        "2. **Slider-crank**: If L = 3r, find max velocity and compare to rω\n",
        "3. **Three-stage gearbox**: Design for 100:1 reduction with realistic gear sizes\n",
        "4. **Rolling cylinder with force**: Horizontal force F applied at center, find acceleration\n",
        "\n",
        "---\n"
    ]
})

# Save notebook
os.makedirs(output_dir, exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("=" * 60)
print("✓ Unit 5 Lecture 2 Created Successfully!")
print("=" * 60)
print(f"\nFile: {output_path}")
print(f"\nNotebook structure:")
print(f"  Total cells: {len(notebook['cells'])}")
print(f"  Markdown: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'markdown')}")
print(f"  Code: {sum(1 for c in notebook['cells'] if c['cell_type'] == 'code')}")
print(f"\nContent:")
print(f"  Part A: Yo-Yo Dynamics (coupled translation-rotation)")
print(f"  Part B: Slider-Crank Mechanism (engine kinematics)")
print(f"  Part C: Gear Trains (speed/torque ratios)")
print(f"\nDuration: ~90 minutes")
print(f"\nReady to test!")
